// faraway united locust-angular/src/app/pages/home/home.component.ts
import { Component } from '@angular/core'
import { Title, Meta } from '@angular/platform-browser'

@Component({
  selector: 'app-home',
  templateUrl: 'home.component.html',
  styleUrls: ['home.component.css'],
})
export class Home {
  raw80ky: string = ' '
  constructor(private title: Title, private meta: Meta) {
    this.title.setTitle('Faraway United Locust')
    this.meta.addTags([
      {
        property: 'og:title',
        content: 'Faraway United Locust',
      },
    ])
  }
}

<div class="home-container">
  <app-navbar8>
    <ng-template #page4Description>
      <div class="home-fragment100">
        <span class="home-text100">Get in touch with us for any inquiries</span>
      </div>
    </ng-template>
    <ng-template #action1>
      <div class="home-fragment101">
        <span class="home-text101">Book Appointment</span>
      </div>
    </ng-template>
    <ng-template #link2>
      <div class="home-fragment102">
        <span class="home-text102">/services</span>
      </div>
    </ng-template>
    <ng-template #page1>
      <div class="home-fragment103"><span class="home-text103">Home</span></div>
    </ng-template>
    <ng-template #link1>
      <div class="home-fragment104">
        <span class="home-text104">/home</span>
      </div>
    </ng-template>
    <ng-template #page4>
      <div class="home-fragment105">
        <span class="home-text105">Contact</span>
      </div>
    </ng-template>
    <ng-template #page2>
      <div class="home-fragment106">
        <span class="home-text106">Services</span>
      </div>
    </ng-template>
    <ng-template #link4>
      <div class="home-fragment107">
        <span class="home-text107">/contact</span>
      </div>
    </ng-template>
    <ng-template #page1Description>
      <div class="home-fragment108">
        <span class="home-text108">
          Welcome to Swasth Saarthi - Your Health Companion
        </span>
      </div>
    </ng-template>
    <ng-template #page2Description>
      <div class="home-fragment109">
        <span class="home-text109">
          Explore our range of healthcare services
        </span>
      </div>
    </ng-template>
    <ng-template #link3>
      <div class="home-fragment110">
        <span class="home-text110">/about</span>
      </div>
    </ng-template>
    <ng-template #page3>
      <div class="home-fragment111">
        <span class="home-text111">About Us</span>
      </div>
    </ng-template>
    <ng-template #page3Description>
      <div class="home-fragment112">
        <span class="home-text112">Learn more about our mission and team</span>
      </div>
    </ng-template>
    <ng-template #action2>
      <div class="home-fragment113">
        <span class="home-text113">Learn More</span>
      </div>
    </ng-template>
  </app-navbar8>
  <app-hero17
    image7Src="https://images.unsplash.com/photo-1584467735871-8e85353a8413?ixid=M3w5MTMyMXwwfDF8c2VhcmNofDIwfHxoZWFsdGglMjBjYXJlfGVufDB8fHx8MTc1NTAxNjkyMXww&amp;ixlib=rb-4.1.0&amp;w=1500"
    image3Src="https://images.unsplash.com/photo-1603398938378-e54eab446dde?ixid=M3w5MTMyMXwwfDF8c2VhcmNofDI2fHxoZWFsdGglMjBjYXJlfGVufDB8fHx8MTc1NTAxNjkyMnww&amp;ixlib=rb-4.1.0&amp;w=1500"
  >
    <ng-template #action2>
      <div class="home-fragment114">
        <span class="home-text114">Learn More</span>
      </div>
    </ng-template>
    <ng-template #action1>
      <div class="home-fragment115">
        <span class="home-text115">Get Started</span>
      </div>
    </ng-template>
    <ng-template #heading1>
      <div class="home-fragment116">
        <span class="home-text116">Welcome to Swasth Saarthi</span>
      </div>
    </ng-template>
    <ng-template #content1>
      <div class="home-fragment117">
        <span class="home-text117">
          Empowering rural and semi-urban communities with accessible and
          affordable healthcare through AI technology.
        </span>
      </div>
    </ng-template>
  </app-hero17>
  <app-features24
    feature1ImgSrc="https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?ixid=M3w5MTMyMXwwfDF8c2VhcmNofDE2fHxoZWFsdGglMjBjYXJlfGVufDB8fHx8MTc1NTAxNjkyMXww&amp;ixlib=rb-4.1.0&amp;w=1500"
  >
    <ng-template #feature3Description>
      <div class="home-fragment118">
        <span class="home-text118">Medicine delivery</span>
      </div>
    </ng-template>
    <ng-template #feature3Title>
      <div class="home-fragment119">
        <span class="home-text119">Medicine Delivery</span>
      </div>
    </ng-template>
    <ng-template #feature2Description>
      <div class="home-fragment120">
        <span class="home-text120">Telemedicine consultations</span>
      </div>
    </ng-template>
    <ng-template #feature1Title>
      <div class="home-fragment121">
        <span class="home-text121">AI Symptom Checker</span>
      </div>
    </ng-template>
    <ng-template #feature1Description>
      <div class="home-fragment122">
        <span class="home-text122">
          AI-powered symptom checker for accurate health assessments
        </span>
      </div>
    </ng-template>
    <ng-template #feature2Title>
      <div class="home-fragment123">
        <span class="home-text123">Telemedicine Consultations</span>
      </div>
    </ng-template>
  </app-features24>
  <app-cta26>
    <ng-template #heading1>
      <div class="home-fragment124">
        <span class="home-text124">Join Swasth Saarthi today!</span>
      </div>
    </ng-template>
    <ng-template #content1>
      <div class="home-fragment125">
        <span class="home-text125">
          Experience accessible and affordable healthcare at your fingertips.
        </span>
      </div>
    </ng-template>
    <ng-template #action1>
      <div class="home-fragment126">
        <span class="home-text126">Sign up now</span>
      </div>
    </ng-template>
  </app-cta26>
  <app-features25
    feature1ImgSrc="https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?ixid=M3w5MTMyMXwwfDF8c2VhcmNofDZ8fGhlYWx0aHxlbnwwfHx8fDE3NTUwMTY5MDN8MA&amp;ixlib=rb-4.1.0&amp;w=1500"
  >
    <ng-template #feature3Description>
      <div class="home-fragment127">
        <span class="home-text127">
          Have your prescribed medications delivered to your doorstep for
          convenience.
        </span>
      </div>
    </ng-template>
    <ng-template #feature1Description>
      <div class="home-fragment128">
        <span class="home-text128">
          Quickly assess your symptoms and get recommendations for next steps.
        </span>
      </div>
    </ng-template>
    <ng-template #feature2Title>
      <div class="home-fragment129">
        <span class="home-text129">Telemedicine Consultations</span>
      </div>
    </ng-template>
    <ng-template #feature1Title>
      <div class="home-fragment130">
        <span class="home-text130">AI Symptom Checker</span>
      </div>
    </ng-template>
    <ng-template #feature2Description>
      <div class="home-fragment131">
        <span class="home-text131">
          Connect with healthcare professionals remotely for medical advice and
          prescriptions.
        </span>
      </div>
    </ng-template>
    <ng-template #feature3Title>
      <div class="home-fragment132">
        <span class="home-text132">Medicine Delivery</span>
      </div>
    </ng-template>
  </app-features25>
  <app-pricing14>
    <ng-template #plan3Price>
      <div class="home-fragment133">
        <span class="home-text133">Starting at $30/month</span>
      </div>
    </ng-template>
    <ng-template #plan3Action>
      <div class="home-fragment134">
        <span class="home-text134">Sign up now</span>
      </div>
    </ng-template>
    <ng-template #plan11>
      <div class="home-fragment135">
        <span class="home-text135">Basic plan</span>
      </div>
    </ng-template>
    <ng-template #plan1Action>
      <div class="home-fragment136">
        <span class="home-text136">Sign up now</span>
      </div>
    </ng-template>
    <ng-template #plan31>
      <div class="home-fragment137">
        <span class="home-text137">Enterprise plan</span>
      </div>
    </ng-template>
    <ng-template #plan3Feature41>
      <div class="home-fragment138">
        <span class="home-text138">Feature text goes here</span>
      </div>
    </ng-template>
    <ng-template #plan1Feature2>
      <div class="home-fragment139">
        <span class="home-text139">Telemedicine consultations</span>
      </div>
    </ng-template>
    <ng-template #plan2Feature11>
      <div class="home-fragment140">
        <span class="home-text140">Feature text goes here</span>
      </div>
    </ng-template>
    <ng-template #plan3Feature51>
      <div class="home-fragment141">
        <span class="home-text141">Feature text goes here</span>
      </div>
    </ng-template>
    <ng-template #plan2Feature41>
      <div class="home-fragment142">
        <span class="home-text142">Feature text goes here</span>
      </div>
    </ng-template>
    <ng-template #plan2Feature2>
      <div class="home-fragment143">
        <span class="home-text143">Telemedicine consultations</span>
      </div>
    </ng-template>
    <ng-template #plan3Feature21>
      <div class="home-fragment144">
        <span class="home-text144">Feature text goes here</span>
      </div>
    </ng-template>
    <ng-template #plan2Feature4>
      <div class="home-fragment145">
        <span class="home-text145">Feature text goes here</span>
      </div>
    </ng-template>
    <ng-template #plan2Yearly>
      <div class="home-fragment146">
        <span class="home-text146">$120/year</span>
      </div>
    </ng-template>
    <ng-template #plan1Action1>
      <div class="home-fragment147">
        <span class="home-text147">Get started</span>
      </div>
    </ng-template>
    <ng-template #plan2Action>
      <div class="home-fragment148">
        <span class="home-text148">Sign up now</span>
      </div>
    </ng-template>
    <ng-template #plan3Feature1>
      <div class="home-fragment149">
        <span class="home-text149">AI symptom checker</span>
      </div>
    </ng-template>
    <ng-template #plan2Feature3>
      <div class="home-fragment150">
        <span class="home-text150">Mood-detecting mental wellness chatbot</span>
      </div>
    </ng-template>
    <ng-template #plan1Price1>
      <div class="home-fragment151">
        <span class="home-text151">$200/yr</span>
      </div>
    </ng-template>
    <ng-template #plan2>
      <div class="home-fragment152">
        <span class="home-text152">Business plan</span>
      </div>
    </ng-template>
    <ng-template #plan2Feature21>
      <div class="home-fragment153">
        <span class="home-text153">Feature text goes here</span>
      </div>
    </ng-template>
    <ng-template #plan2Action1>
      <div class="home-fragment154">
        <span class="home-text154">Get started</span>
      </div>
    </ng-template>
    <ng-template #plan3Feature2>
      <div class="home-fragment155">
        <span class="home-text155">Telemedicine consultations</span>
      </div>
    </ng-template>
    <ng-template #content1>
      <div class="home-fragment156">
        <span class="home-text156">Choose the perfect plan for you</span>
      </div>
    </ng-template>
    <ng-template #plan2Feature1>
      <div class="home-fragment157">
        <span class="home-text157">AI symptom checker</span>
      </div>
    </ng-template>
    <ng-template #heading1>
      <div class="home-fragment158">
        <span class="home-text158">Pricing plan</span>
      </div>
    </ng-template>
    <ng-template #plan3Feature31>
      <div class="home-fragment159">
        <span class="home-text159">Feature text goes here</span>
      </div>
    </ng-template>
    <ng-template #plan1>
      <div class="home-fragment160">
        <span class="home-text160">Basic plan</span>
      </div>
    </ng-template>
    <ng-template #plan21>
      <div class="home-fragment161">
        <span class="home-text161">Business plan</span>
      </div>
    </ng-template>
    <ng-template #plan1Feature11>
      <div class="home-fragment162">
        <span class="home-text162">Feature text goes here</span>
      </div>
    </ng-template>
    <ng-template #plan1Feature21>
      <div class="home-fragment163">
        <span class="home-text163">Feature text goes here</span>
      </div>
    </ng-template>
    <ng-template #plan3Feature5>
      <div class="home-fragment164">
        <span class="home-text164">Feature text goes here</span>
      </div>
    </ng-template>
    <ng-template #plan2Yearly1>
      <div class="home-fragment165">
        <span class="home-text165">or $29 monthly</span>
      </div>
    </ng-template>
    <ng-template #plan2Price>
      <div class="home-fragment166">
        <span class="home-text166">Starting at $15/month</span>
      </div>
    </ng-template>
    <ng-template #plan3Yearly1>
      <div class="home-fragment167">
        <span class="home-text167">or $49 monthly</span>
      </div>
    </ng-template>
    <ng-template #plan2Feature31>
      <div class="home-fragment168">
        <span class="home-text168">Feature text goes here</span>
      </div>
    </ng-template>
    <ng-template #plan3Feature11>
      <div class="home-fragment169">
        <span class="home-text169">Feature text goes here</span>
      </div>
    </ng-template>
    <ng-template #plan1Yearly1>
      <div class="home-fragment170">
        <span class="home-text170">or $20 monthly</span>
      </div>
    </ng-template>
    <ng-template #plan2Price1>
      <div class="home-fragment171">
        <span class="home-text171">$299/yr</span>
      </div>
    </ng-template>
    <ng-template #plan3Yearly>
      <div class="home-fragment172">
        <span class="home-text172">$300/year</span>
      </div>
    </ng-template>
    <ng-template #plan3Feature4>
      <div class="home-fragment173">
        <span class="home-text173">Feature text goes here</span>
      </div>
    </ng-template>
    <ng-template #plan3Price1>
      <div class="home-fragment174">
        <span class="home-text174">$499/yr</span>
      </div>
    </ng-template>
    <ng-template #plan1Feature31>
      <div class="home-fragment175">
        <span class="home-text175">Feature text goes here</span>
      </div>
    </ng-template>
    <ng-template #plan1Feature3>
      <div class="home-fragment176">
        <span class="home-text176">Medicine delivery</span>
      </div>
    </ng-template>
    <ng-template #plan1Yearly>
      <div class="home-fragment177">
        <span class="home-text177">$0/year</span>
      </div>
    </ng-template>
    <ng-template #plan1Feature1>
      <div class="home-fragment178">
        <span class="home-text178">AI symptom checker</span>
      </div>
    </ng-template>
    <ng-template #plan3Feature3>
      <div class="home-fragment179">
        <span class="home-text179">Mood-detecting mental wellness chatbot</span>
      </div>
    </ng-template>
    <ng-template #content2>
      <div class="home-fragment180">
        <span class="home-text180">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          <span [innerHTML]="raw80ky"></span>
        </span>
      </div>
    </ng-template>
    <ng-template #plan3Action1>
      <div class="home-fragment181">
        <span class="home-text181">Get started</span>
      </div>
    </ng-template>
    <ng-template #plan1Price>
      <div class="home-fragment182">
        <span class="home-text182">Starting at $0/month</span>
      </div>
    </ng-template>
    <ng-template #plan3>
      <div class="home-fragment183">
        <span class="home-text183">Enterprise plan</span>
      </div>
    </ng-template>
  </app-pricing14>
  <app-steps2>
    <ng-template #step1Description>
      <div class="home-fragment184">
        <span class="home-text184">
          Create an account using your mobile number and basic details to access
          our telehealth services.
        </span>
      </div>
    </ng-template>
    <ng-template #step3Description>
      <div class="home-fragment185">
        <span class="home-text185">
          Book a virtual appointment with a healthcare provider for a detailed
          diagnosis and treatment plan.
        </span>
      </div>
    </ng-template>
    <ng-template #step2Title>
      <div class="home-fragment186">
        <span class="home-text186">Use AI symptom checker</span>
      </div>
    </ng-template>
    <ng-template #step2Description>
      <div class="home-fragment187">
        <span class="home-text187">
          Describe your symptoms to the AI-powered tool to receive preliminary
          health assessments.
        </span>
      </div>
    </ng-template>
    <ng-template #step1Title>
      <div class="home-fragment188">
        <span class="home-text188">Sign up on Swasth Saarthi platform</span>
      </div>
    </ng-template>
    <ng-template #step3Title>
      <div class="home-fragment189">
        <span class="home-text189">Schedule a telemedicine consultation</span>
      </div>
    </ng-template>
    <ng-template #step4Description>
      <div class="home-fragment190">
        <span class="home-text190">
          Get your prescribed medications delivered to your doorstep for
          convenience and timely treatment.
        </span>
      </div>
    </ng-template>
    <ng-template #step4Title>
      <div class="home-fragment191">
        <span class="home-text191">Receive medicine delivery</span>
      </div>
    </ng-template>
  </app-steps2>
  <app-testimonial17
    author4Src="https://images.unsplash.com/photo-1743345358132-bc60a91716ea?ixid=M3w5MTMyMXwwfDF8YWxsfDEzfHx8fHx8fHwxNzU1MDEyNzc5fA&amp;ixlib=rb-4.1.0&amp;w=1500"
  >
    <ng-template #author2Position>
      <div class="home-fragment192">
        <span class="home-text192">Teacher</span>
      </div>
    </ng-template>
    <ng-template #author1Position>
      <div class="home-fragment193">
        <span class="home-text193">Farmer</span>
      </div>
    </ng-template>
    <ng-template #author1Name>
      <div class="home-fragment194">
        <span class="home-text194">SanjeevPatel</span>
      </div>
    </ng-template>
    <ng-template #author3Name>
      <div class="home-fragment195">
        <span class="home-text195">Riya Singh</span>
      </div>
    </ng-template>
    <ng-template #review2>
      <div class="home-fragment196">
        <span class="home-text196">
          As a teacher in a remote village, accessing healthcare was always a
          challenge. Swasth Saarthi has made it convenient for me to seek
          medical advice and get prescriptions delivered to my doorstep. The
          mental wellness chatbot has also helped me manage stress better.
        </span>
      </div>
    </ng-template>
    <ng-template #author2Name>
      <div class="home-fragment197">
        <span class="home-text197">Aditya Pratap Singh</span>
      </div>
    </ng-template>
    <ng-template #author4Position>
      <div class="home-fragment198">
        <span class="home-text198">Social Worker</span>
      </div>
    </ng-template>
    <ng-template #author4Name>
      <div class="home-fragment199">
        <span class="home-text199">Pawan Singh</span>
      </div>
    </ng-template>
    <ng-template #content1>
      <div class="home-fragment200">
        <span class="home-text200">
          Swasth Saarthi has been a lifesaver for me and my family. I can now
          consult with doctors without traveling long distances, saving time and
          money. The AI symptom checker is incredibly accurate, and the medicine
          delivery service is a blessing.
        </span>
      </div>
    </ng-template>
    <ng-template #author3Position>
      <div class="home-fragment201">
        <span class="home-text201">Local Shop Owner</span>
      </div>
    </ng-template>
    <ng-template #review1>
      <div class="home-fragment202">
        <span class="home-text202">
          Swasth Saarthi has transformed healthcare access in my village. I can
          now connect with doctors without leaving my farm, saving both time and
          money. The platform’s accurate AI symptom checker and timely medicine
          delivery have been a true blessing for my family.
        </span>
      </div>
    </ng-template>
    <ng-template #heading1>
      <div class="home-fragment203">
        <span class="home-text203">Testimonials</span>
      </div>
    </ng-template>
    <ng-template #review3>
      <div class="home-fragment204">
        <span class="home-text204">
          I never thought I could receive quality healthcare services from the
          comfort of my shop until I discovered Swasth Saarthi. The telemedicine
          consultations have been prompt and effective, and the multi-language
          support is a game-changer for our community.
        </span>
      </div>
    </ng-template>
    <ng-template #review4>
      <div class="home-fragment205">
        <span class="home-text205">
          Working with marginalized communities, I have seen firsthand the
          impact of Swasth Saarthi in bridging the healthcare gap. The
          platform&apos;s integration with government programs ensures that even
          the most vulnerable populations have access to essential medical
          services.
        </span>
      </div>
    </ng-template>
  </app-testimonial17>
  <app-footer4>
    <ng-template #link5>
      <div class="home-fragment206"><span class="home-text206">FAQs</span></div>
    </ng-template>
    <ng-template #link3>
      <div class="home-fragment207">
        <span class="home-text207">About Us</span>
      </div>
    </ng-template>
    <ng-template #link1>
      <div class="home-fragment208"><span class="home-text208">Home</span></div>
    </ng-template>
    <ng-template #termsLink>
      <div class="home-fragment209">
        <span class="home-text209">Terms and Conditions</span>
      </div>
    </ng-template>
    <ng-template #link2>
      <div class="home-fragment210">
        <span class="home-text210">Services</span>
      </div>
    </ng-template>
    <ng-template #link4>
      <div class="home-fragment211">
        <span class="home-text211">Contact Us</span>
      </div>
    </ng-template>
    <ng-template #cookiesLink>
      <div class="home-fragment212">
        <span class="home-text212">Cookies Policy</span>
      </div>
    </ng-template>
    <ng-template #privacyLink>
      <div class="home-fragment213">
        <span class="home-text213">Privacy Policy</span>
      </div>
    </ng-template>
  </app-footer4>
</div>

// faraway united locust-react/src/views/home.js
import React, { Fragment } from 'react'

import { Helmet } from 'react-helmet'

import Navbar8 from '../components/navbar8'
import Hero17 from '../components/hero17'
import Features24 from '../components/features24'
import CTA26 from '../components/cta26'
import Features25 from '../components/features25'
import Pricing14 from '../components/pricing14'
import Steps2 from '../components/steps2'
import Testimonial17 from '../components/testimonial17'
import Footer4 from '../components/footer4'
import './home.css'

const Home = (props) => {
  return (
    <div className="home-container">
      <Helmet>
        <title>Faraway United Locust</title>
        <meta property="og:title" content="Faraway United Locust" />
      </Helmet>
      <Navbar8
        page4Description={
          <Fragment>
            <span className="home-text100">
              Get in touch with us for any inquiries
            </span>
          </Fragment>
        }
        action1={
          <Fragment>
            <span className="home-text101">Book Appointment</span>
          </Fragment>
        }
        link2={
          <Fragment>
            <span className="home-text102">/services</span>
          </Fragment>
        }
        page1={
          <Fragment>
            <span className="home-text103">Home</span>
          </Fragment>
        }
        link1={
          <Fragment>
            <span className="home-text104">/home</span>
          </Fragment>
        }
        page4={
          <Fragment>
            <span className="home-text105">Contact</span>
          </Fragment>
        }
        page2={
          <Fragment>
            <span className="home-text106">Services</span>
          </Fragment>
        }
        link4={
          <Fragment>
            <span className="home-text107">/contact</span>
          </Fragment>
        }
        page1Description={
          <Fragment>
            <span className="home-text108">
              Welcome to Swasth Saarthi - Your Health Companion
            </span>
          </Fragment>
        }
        page2Description={
          <Fragment>
            <span className="home-text109">
              Explore our range of healthcare services
            </span>
          </Fragment>
        }
        link3={
          <Fragment>
            <span className="home-text110">/about</span>
          </Fragment>
        }
        page3={
          <Fragment>
            <span className="home-text111">About Us</span>
          </Fragment>
        }
        page3Description={
          <Fragment>
            <span className="home-text112">
              Learn more about our mission and team
            </span>
          </Fragment>
        }
        action2={
          <Fragment>
            <span className="home-text113">Learn More</span>
          </Fragment>
        }
      ></Navbar8>
      <Hero17
        action2={
          <Fragment>
            <span className="home-text114">Learn More</span>
          </Fragment>
        }
        action1={
          <Fragment>
            <span className="home-text115">Get Started</span>
          </Fragment>
        }
        heading1={
          <Fragment>
            <span className="home-text116">Welcome to Swasth Saarthi</span>
          </Fragment>
        }
        content1={
          <Fragment>
            <span className="home-text117">
              Empowering rural and semi-urban communities with accessible and
              affordable healthcare through AI technology.
            </span>
          </Fragment>
        }
        image7Src="https://images.unsplash.com/photo-1584467735871-8e85353a8413?ixid=M3w5MTMyMXwwfDF8c2VhcmNofDIwfHxoZWFsdGglMjBjYXJlfGVufDB8fHx8MTc1NTAxNjkyMXww&amp;ixlib=rb-4.1.0&amp;w=1500"
        image3Src="https://images.unsplash.com/photo-1603398938378-e54eab446dde?ixid=M3w5MTMyMXwwfDF8c2VhcmNofDI2fHxoZWFsdGglMjBjYXJlfGVufDB8fHx8MTc1NTAxNjkyMnww&amp;ixlib=rb-4.1.0&amp;w=1500"
      ></Hero17>
      <Features24
        feature3Description={
          <Fragment>
            <span className="home-text118">Medicine delivery</span>
          </Fragment>
        }
        feature3Title={
          <Fragment>
            <span className="home-text119">Medicine Delivery</span>
          </Fragment>
        }
        feature2Description={
          <Fragment>
            <span className="home-text120">Telemedicine consultations</span>
          </Fragment>
        }
        feature1Title={
          <Fragment>
            <span className="home-text121">AI Symptom Checker</span>
          </Fragment>
        }
        feature1Description={
          <Fragment>
            <span className="home-text122">
              AI-powered symptom checker for accurate health assessments
            </span>
          </Fragment>
        }
        feature2Title={
          <Fragment>
            <span className="home-text123">Telemedicine Consultations</span>
          </Fragment>
        }
        feature1ImgSrc="https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?ixid=M3w5MTMyMXwwfDF8c2VhcmNofDE2fHxoZWFsdGglMjBjYXJlfGVufDB8fHx8MTc1NTAxNjkyMXww&amp;ixlib=rb-4.1.0&amp;w=1500"
      ></Features24>
      <CTA26
        heading1={
          <Fragment>
            <span className="home-text124">Join Swasth Saarthi today!</span>
          </Fragment>
        }
        content1={
          <Fragment>
            <span className="home-text125">
              Experience accessible and affordable healthcare at your
              fingertips.
            </span>
          </Fragment>
        }
        action1={
          <Fragment>
            <span className="home-text126">Sign up now</span>
          </Fragment>
        }
      ></CTA26>
      <Features25
        feature3Description={
          <Fragment>
            <span className="home-text127">
              Have your prescribed medications delivered to your doorstep for
              convenience.
            </span>
          </Fragment>
        }
        feature1Description={
          <Fragment>
            <span className="home-text128">
              Quickly assess your symptoms and get recommendations for next
              steps.
            </span>
          </Fragment>
        }
        feature2Title={
          <Fragment>
            <span className="home-text129">Telemedicine Consultations</span>
          </Fragment>
        }
        feature1Title={
          <Fragment>
            <span className="home-text130">AI Symptom Checker</span>
          </Fragment>
        }
        feature2Description={
          <Fragment>
            <span className="home-text131">
              Connect with healthcare professionals remotely for medical advice
              and prescriptions.
            </span>
          </Fragment>
        }
        feature3Title={
          <Fragment>
            <span className="home-text132">Medicine Delivery</span>
          </Fragment>
        }
        feature1ImgSrc="https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?ixid=M3w5MTMyMXwwfDF8c2VhcmNofDZ8fGhlYWx0aHxlbnwwfHx8fDE3NTUwMTY5MDN8MA&amp;ixlib=rb-4.1.0&amp;w=1500"
      ></Features25>
      <Pricing14
        plan3Price={
          <Fragment>
            <span className="home-text133">Starting at $30/month</span>
          </Fragment>
        }
        plan3Action={
          <Fragment>
            <span className="home-text134">Sign up now</span>
          </Fragment>
        }
        plan11={
          <Fragment>
            <span className="home-text135">Basic plan</span>
          </Fragment>
        }
        plan1Action={
          <Fragment>
            <span className="home-text136">Sign up now</span>
          </Fragment>
        }
        plan31={
          <Fragment>
            <span className="home-text137">Enterprise plan</span>
          </Fragment>
        }
        plan3Feature41={
          <Fragment>
            <span className="home-text138">Feature text goes here</span>
          </Fragment>
        }
        plan1Feature2={
          <Fragment>
            <span className="home-text139">Telemedicine consultations</span>
          </Fragment>
        }
        plan2Feature11={
          <Fragment>
            <span className="home-text140">Feature text goes here</span>
          </Fragment>
        }
        plan3Feature51={
          <Fragment>
            <span className="home-text141">Feature text goes here</span>
          </Fragment>
        }
        plan2Feature41={
          <Fragment>
            <span className="home-text142">Feature text goes here</span>
          </Fragment>
        }
        plan2Feature2={
          <Fragment>
            <span className="home-text143">Telemedicine consultations</span>
          </Fragment>
        }
        plan3Feature21={
          <Fragment>
            <span className="home-text144">Feature text goes here</span>
          </Fragment>
        }
        plan2Feature4={
          <Fragment>
            <span className="home-text145">Feature text goes here</span>
          </Fragment>
        }
        plan2Yearly={
          <Fragment>
            <span className="home-text146">$120/year</span>
          </Fragment>
        }
        plan1Action1={
          <Fragment>
            <span className="home-text147">Get started</span>
          </Fragment>
        }
        plan2Action={
          <Fragment>
            <span className="home-text148">Sign up now</span>
          </Fragment>
        }
        plan3Feature1={
          <Fragment>
            <span className="home-text149">AI symptom checker</span>
          </Fragment>
        }
        plan2Feature3={
          <Fragment>
            <span className="home-text150">
              Mood-detecting mental wellness chatbot
            </span>
          </Fragment>
        }
        plan1Price1={
          <Fragment>
            <span className="home-text151">$200/yr</span>
          </Fragment>
        }
        plan2={
          <Fragment>
            <span className="home-text152">Business plan</span>
          </Fragment>
        }
        plan2Feature21={
          <Fragment>
            <span className="home-text153">Feature text goes here</span>
          </Fragment>
        }
        plan2Action1={
          <Fragment>
            <span className="home-text154">Get started</span>
          </Fragment>
        }
        plan3Feature2={
          <Fragment>
            <span className="home-text155">Telemedicine consultations</span>
          </Fragment>
        }
        content1={
          <Fragment>
            <span className="home-text156">
              Choose the perfect plan for you
            </span>
          </Fragment>
        }
        plan2Feature1={
          <Fragment>
            <span className="home-text157">AI symptom checker</span>
          </Fragment>
        }
        heading1={
          <Fragment>
            <span className="home-text158">Pricing plan</span>
          </Fragment>
        }
        plan3Feature31={
          <Fragment>
            <span className="home-text159">Feature text goes here</span>
          </Fragment>
        }
        plan1={
          <Fragment>
            <span className="home-text160">Basic plan</span>
          </Fragment>
        }
        plan21={
          <Fragment>
            <span className="home-text161">Business plan</span>
          </Fragment>
        }
        plan1Feature11={
          <Fragment>
            <span className="home-text162">Feature text goes here</span>
          </Fragment>
        }
        plan1Feature21={
          <Fragment>
            <span className="home-text163">Feature text goes here</span>
          </Fragment>
        }
        plan3Feature5={
          <Fragment>
            <span className="home-text164">Feature text goes here</span>
          </Fragment>
        }
        plan2Yearly1={
          <Fragment>
            <span className="home-text165">or $29 monthly</span>
          </Fragment>
        }
        plan2Price={
          <Fragment>
            <span className="home-text166">Starting at $15/month</span>
          </Fragment>
        }
        plan3Yearly1={
          <Fragment>
            <span className="home-text167">or $49 monthly</span>
          </Fragment>
        }
        plan2Feature31={
          <Fragment>
            <span className="home-text168">Feature text goes here</span>
          </Fragment>
        }
        plan3Feature11={
          <Fragment>
            <span className="home-text169">Feature text goes here</span>
          </Fragment>
        }
        plan1Yearly1={
          <Fragment>
            <span className="home-text170">or $20 monthly</span>
          </Fragment>
        }
        plan2Price1={
          <Fragment>
            <span className="home-text171">$299/yr</span>
          </Fragment>
        }
        plan3Yearly={
          <Fragment>
            <span className="home-text172">$300/year</span>
          </Fragment>
        }
        plan3Feature4={
          <Fragment>
            <span className="home-text173">Feature text goes here</span>
          </Fragment>
        }
        plan3Price1={
          <Fragment>
            <span className="home-text174">$499/yr</span>
          </Fragment>
        }
        plan1Feature31={
          <Fragment>
            <span className="home-text175">Feature text goes here</span>
          </Fragment>
        }
        plan1Feature3={
          <Fragment>
            <span className="home-text176">Medicine delivery</span>
          </Fragment>
        }
        plan1Yearly={
          <Fragment>
            <span className="home-text177">$0/year</span>
          </Fragment>
        }
        plan1Feature1={
          <Fragment>
            <span className="home-text178">AI symptom checker</span>
          </Fragment>
        }
        plan3Feature3={
          <Fragment>
            <span className="home-text179">
              Mood-detecting mental wellness chatbot
            </span>
          </Fragment>
        }
        content2={
          <Fragment>
            <span className="home-text180">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              <span
                dangerouslySetInnerHTML={{
                  __html: ' ',
                }}
              />
            </span>
          </Fragment>
        }
        plan3Action1={
          <Fragment>
            <span className="home-text181">Get started</span>
          </Fragment>
        }
        plan1Price={
          <Fragment>
            <span className="home-text182">Starting at $0/month</span>
          </Fragment>
        }
        plan3={
          <Fragment>
            <span className="home-text183">Enterprise plan</span>
          </Fragment>
        }
      ></Pricing14>
      <Steps2
        step1Description={
          <Fragment>
            <span className="home-text184">
              Create an account using your mobile number and basic details to
              access our telehealth services.
            </span>
          </Fragment>
        }
        step3Description={
          <Fragment>
            <span className="home-text185">
              Book a virtual appointment with a healthcare provider for a
              detailed diagnosis and treatment plan.
            </span>
          </Fragment>
        }
        step2Title={
          <Fragment>
            <span className="home-text186">Use AI symptom checker</span>
          </Fragment>
        }
        step2Description={
          <Fragment>
            <span className="home-text187">
              Describe your symptoms to the AI-powered tool to receive
              preliminary health assessments.
            </span>
          </Fragment>
        }
        step1Title={
          <Fragment>
            <span className="home-text188">
              Sign up on Swasth Saarthi platform
            </span>
          </Fragment>
        }
        step3Title={
          <Fragment>
            <span className="home-text189">
              Schedule a telemedicine consultation
            </span>
          </Fragment>
        }
        step4Description={
          <Fragment>
            <span className="home-text190">
              Get your prescribed medications delivered to your doorstep for
              convenience and timely treatment.
            </span>
          </Fragment>
        }
        step4Title={
          <Fragment>
            <span className="home-text191">Receive medicine delivery</span>
          </Fragment>
        }
      ></Steps2>
      <Testimonial17
        author2Position={
          <Fragment>
            <span className="home-text192">Teacher</span>
          </Fragment>
        }
        author1Position={
          <Fragment>
            <span className="home-text193">Farmer</span>
          </Fragment>
        }
        author1Name={
          <Fragment>
            <span className="home-text194">SanjeevPatel</span>
          </Fragment>
        }
        author3Name={
          <Fragment>
            <span className="home-text195">Riya Singh</span>
          </Fragment>
        }
        review2={
          <Fragment>
            <span className="home-text196">
              As a teacher in a remote village, accessing healthcare was always
              a challenge. Swasth Saarthi has made it convenient for me to seek
              medical advice and get prescriptions delivered to my doorstep. The
              mental wellness chatbot has also helped me manage stress better.
            </span>
          </Fragment>
        }
        author2Name={
          <Fragment>
            <span className="home-text197">Aditya Pratap Singh</span>
          </Fragment>
        }
        author4Position={
          <Fragment>
            <span className="home-text198">Social Worker</span>
          </Fragment>
        }
        author4Name={
          <Fragment>
            <span className="home-text199">Pawan Singh</span>
          </Fragment>
        }
        content1={
          <Fragment>
            <span className="home-text200">
              Swasth Saarthi has been a lifesaver for me and my family. I can
              now consult with doctors without traveling long distances, saving
              time and money. The AI symptom checker is incredibly accurate, and
              the medicine delivery service is a blessing.
            </span>
          </Fragment>
        }
        author3Position={
          <Fragment>
            <span className="home-text201">Local Shop Owner</span>
          </Fragment>
        }
        review1={
          <Fragment>
            <span className="home-text202">
              Swasth Saarthi has transformed healthcare access in my village. I
              can now connect with doctors without leaving my farm, saving both
              time and money. The platform’s accurate AI symptom checker and
              timely medicine delivery have been a true blessing for my family.
            </span>
          </Fragment>
        }
        heading1={
          <Fragment>
            <span className="home-text203">Testimonials</span>
          </Fragment>
        }
        review3={
          <Fragment>
            <span className="home-text204">
              I never thought I could receive quality healthcare services from
              the comfort of my shop until I discovered Swasth Saarthi. The
              telemedicine consultations have been prompt and effective, and the
              multi-language support is a game-changer for our community.
            </span>
          </Fragment>
        }
        review4={
          <Fragment>
            <span className="home-text205">
              Working with marginalized communities, I have seen firsthand the
              impact of Swasth Saarthi in bridging the healthcare gap. The
              platform&apos;s integration with government programs ensures that
              even the most vulnerable populations have access to essential
              medical services.
            </span>
          </Fragment>
        }
        author4Src="https://images.unsplash.com/photo-1743345358132-bc60a91716ea?ixid=M3w5MTMyMXwwfDF8YWxsfDEzfHx8fHx8fHwxNzU1MDEyNzc5fA&amp;ixlib=rb-4.1.0&amp;w=1500"
      ></Testimonial17>
      <Footer4
        link5={
          <Fragment>
            <span className="home-text206">FAQs</span>
          </Fragment>
        }
        link3={
          <Fragment>
            <span className="home-text207">About Us</span>
          </Fragment>
        }
        link1={
          <Fragment>
            <span className="home-text208">Home</span>
          </Fragment>
        }
        termsLink={
          <Fragment>
            <span className="home-text209">Terms and Conditions</span>
          </Fragment>
        }
        link2={
          <Fragment>
            <span className="home-text210">Services</span>
          </Fragment>
        }
        link4={
          <Fragment>
            <span className="home-text211">Contact Us</span>
          </Fragment>
        }
        cookiesLink={
          <Fragment>
            <span className="home-text212">Cookies Policy</span>
          </Fragment>
        }
        privacyLink={
          <Fragment>
            <span className="home-text213">Privacy Policy</span>
          </Fragment>
        }
      ></Footer4>
    </div>
  )
}

export default Home
