// faraway united locust-angular/src/app/components/contact10/contact10.component.ts
import { Component, Input, ContentChild, TemplateRef } from '@angular/core'

@Component({
  selector: 'app-contact10',
  templateUrl: 'contact10.component.html',
  styleUrls: ['contact10.component.css'],
})
export class Contact10 {
  @ContentChild('content1')
  content1: TemplateRef<any>
  @Input()
  location2ImageSrc: string =
    'https://images.unsplash.com/photo-1558784019-0dade423278b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4MXw&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  location1ImageSrc: string =
    'https://images.unsplash.com/photo-1654856470316-d211472bd107?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4Mnw&ixlib=rb-4.1.0&q=80&w=1080'
  @ContentChild('location1Description')
  location1Description: TemplateRef<any>
  @Input()
  location2ImageAlt: string = 'image2Alt'
  @ContentChild('heading1')
  heading1: TemplateRef<any>
  @ContentChild('location2Description')
  location2Description: TemplateRef<any>
  @Input()
  location1ImageAlt: string = 'image1Alt'
  @ContentChild('location1')
  location1: TemplateRef<any>
  @ContentChild('location2')
  location2: TemplateRef<any>
  constructor() {}
}

<div class="contact10-container1 thq-section-padding">
  <div class="contact10-max-width thq-section-max-width">
    <div class="contact10-content1 thq-flex-row">
      <div class="contact10-content2">
        <h2 class="thq-heading-2">
          <ng-container>
            <ng-template #defaultHeading1>
              <div class="contact10-fragment3">
                <span class="contact10-text18">Locations</span>
              </div>
            </ng-template>
            <ng-container
              *ngTemplateOutlet="heading1 ? heading1 : defaultHeading1"
            ></ng-container>
          </ng-container>
        </h2>
        <p class="thq-body-large">
          <ng-container>
            <ng-template #defaultContent1>
              <div class="contact10-fragment1">
                <span class="contact10-text16">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Suspendisse varius enim in ero.
                </span>
              </div>
            </ng-template>
            <ng-container
              *ngTemplateOutlet="content1 ? content1 : defaultContent1"
            ></ng-container>
          </ng-container>
        </p>
      </div>
    </div>
    <div class="contact10-content3 thq-flex-row">
      <div class="contact10-container2">
        <img
          [attr.alt]="location1ImageAlt"
          [attr.src]="location1ImageSrc"
          class="contact10-image1 thq-img-ratio-16-9"
        />
        <h3 class="contact10-text12 thq-heading-3">
          <ng-container>
            <ng-template #defaultLocation1>
              <div class="contact10-fragment5">
                <span class="contact10-text20">Bucharest</span>
              </div>
            </ng-template>
            <ng-container
              *ngTemplateOutlet="location1 ? location1 : defaultLocation1"
            ></ng-container>
          </ng-container>
        </h3>
        <p class="thq-body-large">
          <ng-container>
            <ng-template #defaultLocation1Description>
              <div class="contact10-fragment2">
                <span class="contact10-text17">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Suspendisse varius enim in ero.
                </span>
              </div>
            </ng-template>
            <ng-container
              *ngTemplateOutlet="location1Description ? location1Description : defaultLocation1Description"
            ></ng-container>
          </ng-container>
        </p>
        <div class="contact10-container3">
          <a
            href="https://example.com"
            target="_blank"
            rel="noreferrer noopener"
            class="thq-button-flat thq-body-small"
          >
            Get directions
          </a>
        </div>
      </div>
      <div class="contact10-container4">
        <img
          [attr.alt]="location2ImageAlt"
          [attr.src]="location2ImageSrc"
          class="contact10-image2 thq-img-ratio-16-9"
        />
        <h3 class="contact10-text14 thq-heading-3">
          <ng-container>
            <ng-template #defaultLocation2>
              <div class="contact10-fragment6">
                <span class="contact10-text21">Cluj - Napoca</span>
              </div>
            </ng-template>
            <ng-container
              *ngTemplateOutlet="location2 ? location2 : defaultLocation2"
            ></ng-container>
          </ng-container>
        </h3>
        <p class="thq-body-large">
          <ng-container>
            <ng-template #defaultLocation2Description>
              <div class="contact10-fragment4">
                <span class="contact10-text19">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Suspendisse varius enim in ero.
                </span>
              </div>
            </ng-template>
            <ng-container
              *ngTemplateOutlet="location2Description ? location2Description : defaultLocation2Description"
            ></ng-container>
          </ng-container>
        </p>
        <div class="contact10-container5">
          <a
            href="https://example.com"
            target="_blank"
            rel="noreferrer noopener"
            class="thq-button-flat thq-body-small"
          >
            Get directions
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

// faraway united locust-react/src/components/contact10.js
import React, { Fragment } from 'react'

import PropTypes from 'prop-types'

import './contact10.css'

const Contact10 = (props) => {
  return (
    <div className="contact10-container1 thq-section-padding">
      <div className="contact10-max-width thq-section-max-width">
        <div className="contact10-content1 thq-flex-row">
          <div className="contact10-content2">
            <h2 className="thq-heading-2">
              {props.heading1 ?? (
                <Fragment>
                  <span className="contact10-text18">Locations</span>
                </Fragment>
              )}
            </h2>
            <p className="thq-body-large">
              {props.content1 ?? (
                <Fragment>
                  <span className="contact10-text16">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Suspendisse varius enim in ero.
                  </span>
                </Fragment>
              )}
            </p>
          </div>
        </div>
        <div className="contact10-content3 thq-flex-row">
          <div className="contact10-container2">
            <img
              alt={props.location1ImageAlt}
              src={props.location1ImageSrc}
              className="contact10-image1 thq-img-ratio-16-9"
            />
            <h3 className="contact10-text12 thq-heading-3">
              {props.location1 ?? (
                <Fragment>
                  <span className="contact10-text20">Bucharest</span>
                </Fragment>
              )}
            </h3>
            <p className="thq-body-large">
              {props.location1Description ?? (
                <Fragment>
                  <span className="contact10-text17">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Suspendisse varius enim in ero.
                  </span>
                </Fragment>
              )}
            </p>
            <div className="contact10-container3">
              <a
                href="https://example.com"
                target="_blank"
                rel="noreferrer noopener"
                className="thq-button-flat thq-body-small"
              >
                Get directions
              </a>
            </div>
          </div>
          <div className="contact10-container4">
            <img
              alt={props.location2ImageAlt}
              src={props.location2ImageSrc}
              className="contact10-image2 thq-img-ratio-16-9"
            />
            <h3 className="contact10-text14 thq-heading-3">
              {props.location2 ?? (
                <Fragment>
                  <span className="contact10-text21">Cluj - Napoca</span>
                </Fragment>
              )}
            </h3>
            <p className="thq-body-large">
              {props.location2Description ?? (
                <Fragment>
                  <span className="contact10-text19">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Suspendisse varius enim in ero.
                  </span>
                </Fragment>
              )}
            </p>
            <div className="contact10-container5">
              <a
                href="https://example.com"
                target="_blank"
                rel="noreferrer noopener"
                className="thq-button-flat thq-body-small"
              >
                Get directions
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

Contact10.defaultProps = {
  content1: undefined,
  location2ImageSrc:
    'https://images.unsplash.com/photo-1558784019-0dade423278b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4MXw&ixlib=rb-4.1.0&q=80&w=1080',
  location1ImageSrc:
    'https://images.unsplash.com/photo-1654856470316-d211472bd107?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4Mnw&ixlib=rb-4.1.0&q=80&w=1080',
  location1Description: undefined,
  location2ImageAlt: 'image2Alt',
  heading1: undefined,
  location2Description: undefined,
  location1ImageAlt: 'image1Alt',
  location1: undefined,
  location2: undefined,
}

Contact10.propTypes = {
  content1: PropTypes.element,
  location2ImageSrc: PropTypes.string,
  location1ImageSrc: PropTypes.string,
  location1Description: PropTypes.element,
  location2ImageAlt: PropTypes.string,
  heading1: PropTypes.element,
  location2Description: PropTypes.element,
  location1ImageAlt: PropTypes.string,
  location1: PropTypes.element,
  location2: PropTypes.element,
}

export default Contact10
