// faraway united locust-angular/src/app/components/cta26/cta26.component.ts
import { Component, Input, ContentChild, TemplateRef } from '@angular/core'

@Component({
  selector: 'app-cta26',
  templateUrl: 'cta26.component.html',
  styleUrls: ['cta26.component.css'],
})
export class CTA26 {
  @ContentChild('heading1')
  heading1: TemplateRef<any>
  @ContentChild('content1')
  content1: TemplateRef<any>
  @ContentChild('action1')
  action1: TemplateRef<any>
  constructor() {}
}

<div class="thq-section-padding">
  <div class="thq-section-max-width">
    <div class="cta26-accent2-bg">
      <div class="cta26-accent1-bg">
        <div class="cta26-container2">
          <div class="cta26-content">
            <span class="thq-heading-2">
              <ng-container>
                <ng-template #defaultHeading1>
                  <div class="cta26-fragment1">
                    <span class="cta26-text4">Join Swasth Saarthi today!</span>
                  </div>
                </ng-template>
                <ng-container
                  *ngTemplateOutlet="heading1 ? heading1 : defaultHeading1"
                ></ng-container>
              </ng-container>
            </span>
            <p class="thq-body-large">
              <ng-container>
                <ng-template #defaultContent1>
                  <div class="cta26-fragment2">
                    <span class="cta26-text5">
                      Experience accessible and affordable healthcare at your
                      fingertips.
                    </span>
                  </div>
                </ng-template>
                <ng-container
                  *ngTemplateOutlet="content1 ? content1 : defaultContent1"
                ></ng-container>
              </ng-container>
            </p>
          </div>
          <div class="cta26-actions">
            <button type="button" class="thq-button-filled cta26-button">
              <span>
                <ng-container>
                  <ng-template #defaultAction1>
                    <div class="cta26-fragment3">
                      <span class="cta26-text6">Sign up now</span>
                    </div>
                  </ng-template>
                  <ng-container
                    *ngTemplateOutlet="action1 ? action1 : defaultAction1"
                  ></ng-container>
                </ng-container>
              </span>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// faraway united locust-react/src/components/cta26.js
import React, { Fragment } from 'react'

import PropTypes from 'prop-types'

import './cta26.css'

const CTA26 = (props) => {
  return (
    <div className="thq-section-padding">
      <div className="thq-section-max-width">
        <div className="cta26-accent2-bg">
          <div className="cta26-accent1-bg">
            <div className="cta26-container2">
              <div className="cta26-content">
                <span className="thq-heading-2">
                  {props.heading1 ?? (
                    <Fragment>
                      <span className="cta26-text4">
                        Join Swasth Saarthi today!
                      </span>
                    </Fragment>
                  )}
                </span>
                <p className="thq-body-large">
                  {props.content1 ?? (
                    <Fragment>
                      <span className="cta26-text5">
                        Experience accessible and affordable healthcare at your
                        fingertips.
                      </span>
                    </Fragment>
                  )}
                </p>
              </div>
              <div className="cta26-actions">
                <button
                  type="button"
                  className="thq-button-filled cta26-button"
                >
                  <span>
                    {props.action1 ?? (
                      <Fragment>
                        <span className="cta26-text6">Sign up now</span>
                      </Fragment>
                    )}
                  </span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

CTA26.defaultProps = {
  heading1: undefined,
  content1: undefined,
  action1: undefined,
}

CTA26.propTypes = {
  heading1: PropTypes.element,
  content1: PropTypes.element,
  action1: PropTypes.element,
}

export default CTA26
