// faraway united locust-angular/src/app/components/features25/features25.component.ts
import { Component, Input, ContentChild, TemplateRef } from '@angular/core'

@Component({
  selector: 'app-features25',
  templateUrl: 'features25.component.html',
  styleUrls: ['features25.component.css'],
})
export class Features25 {
  @ContentChild('feature3Description')
  feature3Description: TemplateRef<any>
  @Input()
  feature1ImgAlt: string = 'AI Symptom Checker Image'
  @ContentChild('feature1Description')
  feature1Description: TemplateRef<any>
  @Input()
  feature3ImgAlt: string = 'Medicine Delivery Image'
  @ContentChild('feature2Title')
  feature2Title: TemplateRef<any>
  @ContentChild('feature1Title')
  feature1Title: TemplateRef<any>
  @Input()
  feature1ImgSrc: string =
    'https://images.unsplash.com/photo-1556219845-95c1847629e0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4Mnw&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  feature3ImgSrc: string =
    'https://images.unsplash.com/photo-1564346340269-7af57915a865?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4M3w&ixlib=rb-4.1.0&q=80&w=1080'
  @ContentChild('feature2Description')
  feature2Description: TemplateRef<any>
  @ContentChild('feature3Title')
  feature3Title: TemplateRef<any>
  @Input()
  feature2ImgAlt: string = 'Telemedicine Consultations Image'
  @Input()
  feature2ImgSrc: string =
    'https://images.unsplash.com/photo-1626200115283-4c0c73f0f4f7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4Nnw&ixlib=rb-4.1.0&q=80&w=1080'
  activeTab: number = 0
  constructor() {}
}

<div class="thq-section-padding">
  <div class="features25-container2 thq-section-max-width">
    <div class="features25-tabs-menu">
      <div (click)="activeTab = 0" class="features25-tab-horizontal1">
        <div class="features25-divider-container1">
          <div *ngIf="activeTab = 0" class="features25-container3"></div>
        </div>
        <div class="features25-content1">
          <h2 class="thq-heading-2">
            <ng-container>
              <ng-template #defaultFeature1Title>
                <div class="features25-fragment4">
                  <span class="features25-text4">AI Symptom Checker</span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="feature1Title ? feature1Title : defaultFeature1Title"
              ></ng-container>
            </ng-container>
          </h2>
          <span class="thq-body-small">
            <ng-container>
              <ng-template #defaultFeature1Description>
                <div class="features25-fragment2">
                  <span class="features25-text2">
                    Quickly assess your symptoms and get recommendations for
                    next steps.
                  </span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="feature1Description ? feature1Description : defaultFeature1Description"
              ></ng-container>
            </ng-container>
          </span>
        </div>
      </div>
      <div (click)="activeTab = 1" class="features25-tab-horizontal2">
        <div class="features25-divider-container2">
          <div *ngIf="activeTab = 1" class="features25-container4"></div>
        </div>
        <div class="features25-content2">
          <h2 class="thq-heading-2">
            <ng-container>
              <ng-template #defaultFeature2Title>
                <div class="features25-fragment3">
                  <span class="features25-text3">
                    Telemedicine Consultations
                  </span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="feature2Title ? feature2Title : defaultFeature2Title"
              ></ng-container>
            </ng-container>
          </h2>
          <span class="thq-body-small">
            <ng-container>
              <ng-template #defaultFeature2Description>
                <div class="features25-fragment5">
                  <span class="features25-text5">
                    Connect with healthcare professionals remotely for medical
                    advice and prescriptions.
                  </span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="feature2Description ? feature2Description : defaultFeature2Description"
              ></ng-container>
            </ng-container>
          </span>
        </div>
      </div>
      <div (click)="activeTab = 2" class="features25-tab-horizontal3">
        <div class="features25-divider-container3">
          <div *ngIf="activeTab = 2" class="features25-container5"></div>
        </div>
        <div class="features25-content3">
          <h2 class="thq-heading-2">
            <ng-container>
              <ng-template #defaultFeature3Title>
                <div class="features25-fragment6">
                  <span class="features25-text6">Medicine Delivery</span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="feature3Title ? feature3Title : defaultFeature3Title"
              ></ng-container>
            </ng-container>
          </h2>
          <span class="thq-body-small">
            <ng-container>
              <ng-template #defaultFeature3Description>
                <div class="features25-fragment1">
                  <span class="features25-text1">
                    Have your prescribed medications delivered to your doorstep
                    for convenience.
                  </span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="feature3Description ? feature3Description : defaultFeature3Description"
              ></ng-container>
            </ng-container>
          </span>
        </div>
      </div>
    </div>
    <div class="features25-image-container">
      <img
        [attr.alt]="feature1ImgAlt"
        [attr.src]="feature1ImgSrc"
        *ngIf="activeTab = 0"
        class="features25-image1 thq-img-ratio-16-9"
      />
      <img
        [attr.alt]="feature2ImgAlt"
        [attr.src]="feature2ImgSrc"
        *ngIf="activeTab = 1"
        class="features25-image2 thq-img-ratio-16-9"
      />
      <img
        [attr.alt]="feature3ImgAlt"
        [attr.src]="feature3ImgSrc"
        *ngIf="activeTab = 2"
        class="features25-image3 thq-img-ratio-16-9"
      />
    </div>
  </div>
</div>

// faraway united locust-react/src/components/features25.js
import React, { useState, Fragment } from 'react'

import PropTypes from 'prop-types'

import './features25.css'

const Features25 = (props) => {
  const [activeTab, setActiveTab] = useState(0)
  return (
    <div className="thq-section-padding">
      <div className="features25-container2 thq-section-max-width">
        <div className="features25-tabs-menu">
          <div
            onClick={() => setActiveTab(0)}
            className="features25-tab-horizontal1"
          >
            <div className="features25-divider-container1">
              {activeTab === 0 && <div className="features25-container3"></div>}
            </div>
            <div className="features25-content1">
              <h2 className="thq-heading-2">
                {props.feature1Title ?? (
                  <Fragment>
                    <span className="features25-text4">AI Symptom Checker</span>
                  </Fragment>
                )}
              </h2>
              <span className="thq-body-small">
                {props.feature1Description ?? (
                  <Fragment>
                    <span className="features25-text2">
                      Quickly assess your symptoms and get recommendations for
                      next steps.
                    </span>
                  </Fragment>
                )}
              </span>
            </div>
          </div>
          <div
            onClick={() => setActiveTab(1)}
            className="features25-tab-horizontal2"
          >
            <div className="features25-divider-container2">
              {activeTab === 1 && <div className="features25-container4"></div>}
            </div>
            <div className="features25-content2">
              <h2 className="thq-heading-2">
                {props.feature2Title ?? (
                  <Fragment>
                    <span className="features25-text3">
                      Telemedicine Consultations
                    </span>
                  </Fragment>
                )}
              </h2>
              <span className="thq-body-small">
                {props.feature2Description ?? (
                  <Fragment>
                    <span className="features25-text5">
                      Connect with healthcare professionals remotely for medical
                      advice and prescriptions.
                    </span>
                  </Fragment>
                )}
              </span>
            </div>
          </div>
          <div
            onClick={() => setActiveTab(2)}
            className="features25-tab-horizontal3"
          >
            <div className="features25-divider-container3">
              {activeTab === 2 && <div className="features25-container5"></div>}
            </div>
            <div className="features25-content3">
              <h2 className="thq-heading-2">
                {props.feature3Title ?? (
                  <Fragment>
                    <span className="features25-text6">Medicine Delivery</span>
                  </Fragment>
                )}
              </h2>
              <span className="thq-body-small">
                {props.feature3Description ?? (
                  <Fragment>
                    <span className="features25-text1">
                      Have your prescribed medications delivered to your
                      doorstep for convenience.
                    </span>
                  </Fragment>
                )}
              </span>
            </div>
          </div>
        </div>
        <div className="features25-image-container">
          {activeTab === 0 && (
            <img
              alt={props.feature1ImgAlt}
              src={props.feature1ImgSrc}
              className="features25-image1 thq-img-ratio-16-9"
            />
          )}
          {activeTab === 1 && (
            <img
              alt={props.feature2ImgAlt}
              src={props.feature2ImgSrc}
              className="features25-image2 thq-img-ratio-16-9"
            />
          )}
          {activeTab === 2 && (
            <img
              alt={props.feature3ImgAlt}
              src={props.feature3ImgSrc}
              className="features25-image3 thq-img-ratio-16-9"
            />
          )}
        </div>
      </div>
    </div>
  )
}

Features25.defaultProps = {
  feature3Description: undefined,
  feature1ImgAlt: 'AI Symptom Checker Image',
  feature1Description: undefined,
  feature3ImgAlt: 'Medicine Delivery Image',
  feature2Title: undefined,
  feature1Title: undefined,
  feature1ImgSrc:
    'https://images.unsplash.com/photo-1556219845-95c1847629e0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4Mnw&ixlib=rb-4.1.0&q=80&w=1080',
  feature3ImgSrc:
    'https://images.unsplash.com/photo-1564346340269-7af57915a865?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4M3w&ixlib=rb-4.1.0&q=80&w=1080',
  feature2Description: undefined,
  feature3Title: undefined,
  feature2ImgAlt: 'Telemedicine Consultations Image',
  feature2ImgSrc:
    'https://images.unsplash.com/photo-1626200115283-4c0c73f0f4f7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4Nnw&ixlib=rb-4.1.0&q=80&w=1080',
}

Features25.propTypes = {
  feature3Description: PropTypes.element,
  feature1ImgAlt: PropTypes.string,
  feature1Description: PropTypes.element,
  feature3ImgAlt: PropTypes.string,
  feature2Title: PropTypes.element,
  feature1Title: PropTypes.element,
  feature1ImgSrc: PropTypes.string,
  feature3ImgSrc: PropTypes.string,
  feature2Description: PropTypes.element,
  feature3Title: PropTypes.element,
  feature2ImgAlt: PropTypes.string,
  feature2ImgSrc: PropTypes.string,
}

export default Features25
