// faraway united locust-angular/src/app/components/footer4/footer4.component.ts
import { Component, Input, ContentChild, TemplateRef } from '@angular/core'

@Component({
  selector: 'app-footer4',
  templateUrl: 'footer4.component.html',
  styleUrls: ['footer4.component.css'],
})
export class Footer4 {
  @ContentChild('link5')
  link5: TemplateRef<any>
  @ContentChild('link3')
  link3: TemplateRef<any>
  @ContentChild('link1')
  link1: TemplateRef<any>
  @ContentChild('termsLink')
  termsLink: TemplateRef<any>
  @ContentChild('link2')
  link2: TemplateRef<any>
  @ContentChild('link4')
  link4: TemplateRef<any>
  @ContentChild('cookiesLink')
  cookiesLink: TemplateRef<any>
  @ContentChild('privacyLink')
  privacyLink: TemplateRef<any>
  constructor() {}
}

<footer class="footer4-footer7 thq-section-padding">
  <div class="footer4-max-width thq-section-max-width">
    <div class="footer4-content">
      <div class="footer4-logo"></div>
      <div class="footer4-links">
        <a
          href="https://example.com"
          target="_blank"
          rel="noreferrer noopener"
          class="thq-body-small"
        >
          <ng-container>
            <ng-template #defaultLink1>
              <div class="footer4-fragment3">
                <span class="footer4-text15">Home</span>
              </div>
            </ng-template>
            <ng-container
              *ngTemplateOutlet="link1 ? link1 : defaultLink1"
            ></ng-container>
          </ng-container>
        </a>
        <a
          href="https://example.com"
          target="_blank"
          rel="noreferrer noopener"
          class="thq-body-small"
        >
          <ng-container>
            <ng-template #defaultLink2>
              <div class="footer4-fragment5">
                <span class="footer4-text17">Services</span>
              </div>
            </ng-template>
            <ng-container
              *ngTemplateOutlet="link2 ? link2 : defaultLink2"
            ></ng-container>
          </ng-container>
        </a>
        <a
          href="https://example.com"
          target="_blank"
          rel="noreferrer noopener"
          class="thq-body-small"
        >
          <ng-container>
            <ng-template #defaultLink3>
              <div class="footer4-fragment2">
                <span class="footer4-text14">About Us</span>
              </div>
            </ng-template>
            <ng-container
              *ngTemplateOutlet="link3 ? link3 : defaultLink3"
            ></ng-container>
          </ng-container>
        </a>
        <a
          href="https://example.com"
          target="_blank"
          rel="noreferrer noopener"
          class="thq-body-small"
        >
          <ng-container>
            <ng-template #defaultLink4>
              <div class="footer4-fragment6">
                <span class="footer4-text18">Contact Us</span>
              </div>
            </ng-template>
            <ng-container
              *ngTemplateOutlet="link4 ? link4 : defaultLink4"
            ></ng-container>
          </ng-container>
        </a>
        <a
          href="https://example.com"
          target="_blank"
          rel="noreferrer noopener"
          class="thq-body-small"
        >
          <ng-container>
            <ng-template #defaultLink5>
              <div class="footer4-fragment1">
                <span class="footer4-text13">FAQs</span>
              </div>
            </ng-template>
            <ng-container
              *ngTemplateOutlet="link5 ? link5 : defaultLink5"
            ></ng-container>
          </ng-container>
        </a>
      </div>
    </div>
    <div class="footer4-credits">
      <div class="thq-divider-horizontal"></div>
      <div class="footer4-row">
        <div class="footer4-container"></div>
        <div class="footer4-footer-links">
          <span class="footer4-text10 thq-body-small">
            <ng-container>
              <ng-template #defaultPrivacyLink>
                <div class="footer4-fragment8">
                  <span class="footer4-text20">Privacy Policy</span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="privacyLink ? privacyLink : defaultPrivacyLink"
              ></ng-container>
            </ng-container>
          </span>
          <span class="thq-body-small">
            <ng-container>
              <ng-template #defaultTermsLink>
                <div class="footer4-fragment4">
                  <span class="footer4-text16">Terms and Conditions</span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="termsLink ? termsLink : defaultTermsLink"
              ></ng-container>
            </ng-container>
          </span>
          <span class="thq-body-small">
            <ng-container>
              <ng-template #defaultCookiesLink>
                <div class="footer4-fragment7">
                  <span class="footer4-text19">Cookies Policy</span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="cookiesLink ? cookiesLink : defaultCookiesLink"
              ></ng-container>
            </ng-container>
          </span>
        </div>
      </div>
    </div>
  </div>
</footer>

// faraway united locust-react/src/components/footer4.js
import React, { Fragment } from 'react'

import PropTypes from 'prop-types'

import './footer4.css'

const Footer4 = (props) => {
  return (
    <footer className="footer4-footer7 thq-section-padding">
      <div className="footer4-max-width thq-section-max-width">
        <div className="footer4-content">
          <div className="footer4-logo"></div>
          <div className="footer4-links">
            <a
              href="https://example.com"
              target="_blank"
              rel="noreferrer noopener"
              className="thq-body-small"
            >
              {props.link1 ?? (
                <Fragment>
                  <span className="footer4-text15">Home</span>
                </Fragment>
              )}
            </a>
            <a
              href="https://example.com"
              target="_blank"
              rel="noreferrer noopener"
              className="thq-body-small"
            >
              {props.link2 ?? (
                <Fragment>
                  <span className="footer4-text17">Services</span>
                </Fragment>
              )}
            </a>
            <a
              href="https://example.com"
              target="_blank"
              rel="noreferrer noopener"
              className="thq-body-small"
            >
              {props.link3 ?? (
                <Fragment>
                  <span className="footer4-text14">About Us</span>
                </Fragment>
              )}
            </a>
            <a
              href="https://example.com"
              target="_blank"
              rel="noreferrer noopener"
              className="thq-body-small"
            >
              {props.link4 ?? (
                <Fragment>
                  <span className="footer4-text18">Contact Us</span>
                </Fragment>
              )}
            </a>
            <a
              href="https://example.com"
              target="_blank"
              rel="noreferrer noopener"
              className="thq-body-small"
            >
              {props.link5 ?? (
                <Fragment>
                  <span className="footer4-text13">FAQs</span>
                </Fragment>
              )}
            </a>
          </div>
        </div>
        <div className="footer4-credits">
          <div className="thq-divider-horizontal"></div>
          <div className="footer4-row">
            <div className="footer4-container"></div>
            <div className="footer4-footer-links">
              <span className="footer4-text10 thq-body-small">
                {props.privacyLink ?? (
                  <Fragment>
                    <span className="footer4-text20">Privacy Policy</span>
                  </Fragment>
                )}
              </span>
              <span className="thq-body-small">
                {props.termsLink ?? (
                  <Fragment>
                    <span className="footer4-text16">Terms and Conditions</span>
                  </Fragment>
                )}
              </span>
              <span className="thq-body-small">
                {props.cookiesLink ?? (
                  <Fragment>
                    <span className="footer4-text19">Cookies Policy</span>
                  </Fragment>
                )}
              </span>
            </div>
          </div>
        </div>
      </div>
    </footer>
  )
}

Footer4.defaultProps = {
  link5: undefined,
  link3: undefined,
  link1: undefined,
  termsLink: undefined,
  link2: undefined,
  link4: undefined,
  cookiesLink: undefined,
  privacyLink: undefined,
}

Footer4.propTypes = {
  link5: PropTypes.element,
  link3: PropTypes.element,
  link1: PropTypes.element,
  termsLink: PropTypes.element,
  link2: PropTypes.element,
  link4: PropTypes.element,
  cookiesLink: PropTypes.element,
  privacyLink: PropTypes.element,
}

export default Footer4
