// faraway united locust-angular/src/app/components/hero17/hero17.component.ts
import { Component, Input, ContentChild, TemplateRef } from '@angular/core'

@Component({
  selector: 'app-hero17',
  templateUrl: 'hero17.component.html',
  styleUrls: ['hero17.component.css'],
})
export class Hero17 {
  @Input()
  image3Src: string =
    'https://images.unsplash.com/photo-1587370560942-ad2a04eabb6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4MXw&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  image8Alt: string = 'Hero Image'
  @Input()
  image2Src: string =
    'https://images.unsplash.com/photo-1556231673-79c47d27cde0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4M3w&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  image6Alt: string = 'Low-bandwidth optimization'
  @Input()
  image11Src: string =
    'https://images.unsplash.com/photo-1709634539435-f9fccaf0fda1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4NXw&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  image5Alt: string = 'Multi-language support'
  @Input()
  image1Alt: string = 'AI-powered telehealth platform'
  @Input()
  image7Src: string =
    'https://images.unsplash.com/photo-1602343457704-131bcf6e21b2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4Nnw&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  image7Alt: string = 'Integration with government and corporate programs'
  @Input()
  image12Alt: string = 'Hero Image'
  @Input()
  image2Alt: string = 'Telemedicine consultations'
  @Input()
  image6Src: string =
    'https://images.unsplash.com/photo-1680009084520-42528e128a0e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4N3w&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  image12Src: string =
    'https://images.unsplash.com/photo-1576132138123-e3dd4b4b233b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4N3w&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  image3Alt: string = 'Medicine delivery'
  @Input()
  image9Src: string =
    'https://images.unsplash.com/photo-1538389400446-14fdb67e9000?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4OHw&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  image11Alt: string = 'Hero Image'
  @ContentChild('action2')
  action2: TemplateRef<any>
  @ContentChild('action1')
  action1: TemplateRef<any>
  @Input()
  image8Src: string =
    'https://images.unsplash.com/photo-1656229818787-7d5a3b3cab6a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4OHw&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  image5Src: string =
    'https://images.unsplash.com/photo-1569153336922-4d72d778735c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4OXw&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  image4Src: string =
    'https://images.unsplash.com/photo-1493655161922-ef98929de9d8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4OXw&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  image10Alt: string = 'Hero Image'
  @Input()
  image4Alt: string = 'Mood-detecting mental wellness chatbot'
  @ContentChild('heading1')
  heading1: TemplateRef<any>
  @ContentChild('content1')
  content1: TemplateRef<any>
  @Input()
  image10Src: string =
    'https://images.unsplash.com/photo-1662284972119-b83a58515a15?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE5MHw&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  image9Alt: string = 'Hero Image'
  @Input()
  image1Src: string =
    'https://images.unsplash.com/photo-1594746214383-521df4590053?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE5MXw&ixlib=rb-4.1.0&q=80&w=1080'
  constructor() {}
}

<div class="hero17-header78">
  <div class="hero17-column thq-section-padding thq-section-max-width">
    <div class="hero17-content1">
      <h1 class="hero17-text1 thq-heading-1">
        <ng-container>
          <ng-template #defaultHeading1>
            <div class="hero17-fragment3">
              <span class="hero17-text7">Welcome to Swasth Saarthi</span>
            </div>
          </ng-template>
          <ng-container
            *ngTemplateOutlet="heading1 ? heading1 : defaultHeading1"
          ></ng-container>
        </ng-container>
      </h1>
      <p class="hero17-text2 thq-body-large">
        <ng-container>
          <ng-template #defaultContent1>
            <div class="hero17-fragment4">
              <span class="hero17-text8">
                Empowering rural and semi-urban communities with accessible and
                affordable healthcare through AI technology.
              </span>
            </div>
          </ng-template>
          <ng-container
            *ngTemplateOutlet="content1 ? content1 : defaultContent1"
          ></ng-container>
        </ng-container>
      </p>
    </div>
    <div class="hero17-actions">
      <button class="thq-button-filled hero17-button1">
        <span class="thq-body-small">
          <ng-container>
            <ng-template #defaultAction1>
              <div class="hero17-fragment2">
                <span class="hero17-text6">Get Started</span>
              </div>
            </ng-template>
            <ng-container
              *ngTemplateOutlet="action1 ? action1 : defaultAction1"
            ></ng-container>
          </ng-container>
        </span>
      </button>
      <button class="thq-button-outline hero17-button2">
        <span class="thq-body-small">
          <ng-container>
            <ng-template #defaultAction2>
              <div class="hero17-fragment1">
                <span class="hero17-text5">Learn More</span>
              </div>
            </ng-template>
            <ng-container
              *ngTemplateOutlet="action2 ? action2 : defaultAction2"
            ></ng-container>
          </ng-container>
        </span>
      </button>
    </div>
  </div>
  <div class="hero17-content2">
    <div
      class="hero17-row-container1 thq-animated-group-container-horizontal thq-mask-image-horizontal"
    >
      <div class="thq-animated-group-horizontal">
        <img
          [attr.alt]="image1Alt"
          [attr.src]="image1Src"
          class="hero17-placeholder-image10 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          [attr.alt]="image2Alt"
          [attr.src]="image2Src"
          class="hero17-placeholder-image11 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          [attr.alt]="image3Alt"
          [attr.src]="image3Src"
          class="hero17-placeholder-image12 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          [attr.alt]="image4Alt"
          [attr.src]="image4Src"
          class="hero17-placeholder-image13 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          [attr.alt]="image5Alt"
          [attr.src]="image5Src"
          class="hero17-placeholder-image14 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          [attr.alt]="image6Alt"
          [attr.src]="image6Src"
          class="hero17-placeholder-image15 thq-img-scale thq-img-ratio-1-1"
        />
      </div>
      <div class="thq-animated-group-horizontal">
        <img
          [attr.alt]="image1Alt"
          [attr.src]="image1Src"
          class="hero17-placeholder-image16 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          [attr.alt]="image2Alt"
          [attr.src]="image2Src"
          class="hero17-placeholder-image17 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          [attr.alt]="image3Alt"
          [attr.src]="image3Src"
          class="hero17-placeholder-image18 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          [attr.alt]="image4Alt"
          [attr.src]="image4Src"
          class="hero17-placeholder-image19 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          [attr.alt]="image5Alt"
          [attr.src]="image5Src"
          class="hero17-placeholder-image20 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          alt="Hero Image"
          src="https://images.unsplash.com/photo-1534312527009-56c7016453e6?ixid=M3w5MTMyMXwwfDF8c2VhcmNofDIxfHxhYnN0cmFjdHxlbnwwfHx8fDE3MTA4NzA5MzB8MA&amp;ixlib=rb-4.0.3&amp;w=1500"
          class="hero17-placeholder-image21 thq-img-scale thq-img-ratio-1-1"
        />
      </div>
    </div>
    <div
      class="hero17-row-container2 thq-animated-group-container-horizontal thq-mask-image-horizontal"
    >
      <div class="thq-animated-group-horizontal-reverse">
        <img
          [attr.alt]="image7Alt"
          [attr.src]="image7Src"
          class="hero17-placeholder-image22 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          [attr.alt]="image8Alt"
          [attr.src]="image8Src"
          class="hero17-placeholder-image23 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          [attr.alt]="image9Alt"
          [attr.src]="image9Src"
          class="hero17-placeholder-image24 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          [attr.alt]="image10Alt"
          [attr.src]="image10Src"
          class="hero17-placeholder-image25 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          [attr.alt]="image11Alt"
          [attr.src]="image11Src"
          class="hero17-placeholder-image26 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          [attr.alt]="image12Alt"
          [attr.src]="image12Src"
          class="hero17-placeholder-image27 thq-img-scale thq-img-ratio-1-1"
        />
      </div>
      <div class="thq-animated-group-horizontal-reverse">
        <img
          [attr.alt]="image7Alt"
          [attr.src]="image7Src"
          class="hero17-placeholder-image28 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          [attr.alt]="image8Alt"
          [attr.src]="image8Src"
          class="hero17-placeholder-image29 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          [attr.alt]="image9Alt"
          [attr.src]="image9Src"
          class="hero17-placeholder-image30 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          [attr.alt]="image10Alt"
          [attr.src]="image10Src"
          class="hero17-placeholder-image31 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          [attr.alt]="image11Alt"
          [attr.src]="image11Src"
          class="hero17-placeholder-image32 thq-img-scale thq-img-ratio-1-1"
        />
        <img
          alt="Hero Image"
          src="https://images.unsplash.com/photo-1568214379698-8aeb8c6c6ac8?ixid=M3w5MTMyMXwwfDF8c2VhcmNofDEyfHxncmFmaWN8ZW58MHx8fHwxNzE1Nzk0OTk5fDA&amp;ixlib=rb-4.0.3&amp;w=1500"
          class="hero17-placeholder-image33 thq-img-scale thq-img-ratio-1-1"
        />
      </div>
    </div>
  </div>
  <div>
    <div class="hero17-container2">
      <dangerous-html
        html="<style>
  @keyframes scroll-x {
    from {
      transform: translateX(0);
    }
    to {
      transform: translateX(calc(-100% - 16px));
    }
  }

  @keyframes scroll-y {
    from {
      transform: translateY(0);
    }
    to {
      transform: translateY(calc(-100% - 16px));
    }
  }
</style>
"
      ></dangerous-html>
    </div>
  </div>
</div>

// faraway united locust-react/src/components/hero17.js
import React, { Fragment } from 'react'

import Script from 'dangerous-html/react'
import PropTypes from 'prop-types'

import './hero17.css'

const Hero17 = (props) => {
  return (
    <div className="hero17-header78">
      <div className="hero17-column thq-section-padding thq-section-max-width">
        <div className="hero17-content1">
          <h1 className="hero17-text1 thq-heading-1">
            {props.heading1 ?? (
              <Fragment>
                <span className="hero17-text7">Welcome to Swasth Saarthi</span>
              </Fragment>
            )}
          </h1>
          <p className="hero17-text2 thq-body-large">
            {props.content1 ?? (
              <Fragment>
                <span className="hero17-text8">
                  Empowering rural and semi-urban communities with accessible
                  and affordable healthcare through AI technology.
                </span>
              </Fragment>
            )}
          </p>
        </div>
        <div className="hero17-actions">
          <button className="thq-button-filled hero17-button1">
            <span className="thq-body-small">
              {props.action1 ?? (
                <Fragment>
                  <span className="hero17-text6">Get Started</span>
                </Fragment>
              )}
            </span>
          </button>
          <button className="thq-button-outline hero17-button2">
            <span className="thq-body-small">
              {props.action2 ?? (
                <Fragment>
                  <span className="hero17-text5">Learn More</span>
                </Fragment>
              )}
            </span>
          </button>
        </div>
      </div>
      <div className="hero17-content2">
        <div className="hero17-row-container1 thq-animated-group-container-horizontal thq-mask-image-horizontal">
          <div className="thq-animated-group-horizontal">
            <img
              alt={props.image1Alt}
              src={props.image1Src}
              className="hero17-placeholder-image10 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt={props.image2Alt}
              src={props.image2Src}
              className="hero17-placeholder-image11 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt={props.image3Alt}
              src={props.image3Src}
              className="hero17-placeholder-image12 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt={props.image4Alt}
              src={props.image4Src}
              className="hero17-placeholder-image13 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt={props.image5Alt}
              src={props.image5Src}
              className="hero17-placeholder-image14 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt={props.image6Alt}
              src={props.image6Src}
              className="hero17-placeholder-image15 thq-img-scale thq-img-ratio-1-1"
            />
          </div>
          <div className="thq-animated-group-horizontal">
            <img
              alt={props.image1Alt}
              src={props.image1Src}
              className="hero17-placeholder-image16 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt={props.image2Alt}
              src={props.image2Src}
              className="hero17-placeholder-image17 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt={props.image3Alt}
              src={props.image3Src}
              className="hero17-placeholder-image18 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt={props.image4Alt}
              src={props.image4Src}
              className="hero17-placeholder-image19 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt={props.image5Alt}
              src={props.image5Src}
              className="hero17-placeholder-image20 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt="Hero Image"
              src="https://images.unsplash.com/photo-1534312527009-56c7016453e6?ixid=M3w5MTMyMXwwfDF8c2VhcmNofDIxfHxhYnN0cmFjdHxlbnwwfHx8fDE3MTA4NzA5MzB8MA&amp;ixlib=rb-4.0.3&amp;w=1500"
              className="hero17-placeholder-image21 thq-img-scale thq-img-ratio-1-1"
            />
          </div>
        </div>
        <div className="hero17-row-container2 thq-animated-group-container-horizontal thq-mask-image-horizontal">
          <div className="thq-animated-group-horizontal-reverse">
            <img
              alt={props.image7Alt}
              src={props.image7Src}
              className="hero17-placeholder-image22 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt={props.image8Alt}
              src={props.image8Src}
              className="hero17-placeholder-image23 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt={props.image9Alt}
              src={props.image9Src}
              className="hero17-placeholder-image24 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt={props.image10Alt}
              src={props.image10Src}
              className="hero17-placeholder-image25 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt={props.image11Alt}
              src={props.image11Src}
              className="hero17-placeholder-image26 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt={props.image12Alt}
              src={props.image12Src}
              className="hero17-placeholder-image27 thq-img-scale thq-img-ratio-1-1"
            />
          </div>
          <div className="thq-animated-group-horizontal-reverse">
            <img
              alt={props.image7Alt}
              src={props.image7Src}
              className="hero17-placeholder-image28 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt={props.image8Alt}
              src={props.image8Src}
              className="hero17-placeholder-image29 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt={props.image9Alt}
              src={props.image9Src}
              className="hero17-placeholder-image30 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt={props.image10Alt}
              src={props.image10Src}
              className="hero17-placeholder-image31 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt={props.image11Alt}
              src={props.image11Src}
              className="hero17-placeholder-image32 thq-img-scale thq-img-ratio-1-1"
            />
            <img
              alt="Hero Image"
              src="https://images.unsplash.com/photo-1568214379698-8aeb8c6c6ac8?ixid=M3w5MTMyMXwwfDF8c2VhcmNofDEyfHxncmFmaWN8ZW58MHx8fHwxNzE1Nzk0OTk5fDA&amp;ixlib=rb-4.0.3&amp;w=1500"
              className="hero17-placeholder-image33 thq-img-scale thq-img-ratio-1-1"
            />
          </div>
        </div>
      </div>
      <div>
        <div className="hero17-container2">
          <Script
            html={`<style>
  @keyframes scroll-x {
    from {
      transform: translateX(0);
    }
    to {
      transform: translateX(calc(-100% - 16px));
    }
  }

  @keyframes scroll-y {
    from {
      transform: translateY(0);
    }
    to {
      transform: translateY(calc(-100% - 16px));
    }
  }
</style>
`}
          ></Script>
        </div>
      </div>
    </div>
  )
}

Hero17.defaultProps = {
  image3Src:
    'https://images.unsplash.com/photo-1587370560942-ad2a04eabb6d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4MXw&ixlib=rb-4.1.0&q=80&w=1080',
  image8Alt: 'Hero Image',
  image2Src:
    'https://images.unsplash.com/photo-1556231673-79c47d27cde0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4M3w&ixlib=rb-4.1.0&q=80&w=1080',
  image6Alt: 'Low-bandwidth optimization',
  image11Src:
    'https://images.unsplash.com/photo-1709634539435-f9fccaf0fda1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4NXw&ixlib=rb-4.1.0&q=80&w=1080',
  image5Alt: 'Multi-language support',
  image1Alt: 'AI-powered telehealth platform',
  image7Src:
    'https://images.unsplash.com/photo-1602343457704-131bcf6e21b2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4Nnw&ixlib=rb-4.1.0&q=80&w=1080',
  image7Alt: 'Integration with government and corporate programs',
  image12Alt: 'Hero Image',
  image2Alt: 'Telemedicine consultations',
  image6Src:
    'https://images.unsplash.com/photo-1680009084520-42528e128a0e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4N3w&ixlib=rb-4.1.0&q=80&w=1080',
  image12Src:
    'https://images.unsplash.com/photo-1576132138123-e3dd4b4b233b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4N3w&ixlib=rb-4.1.0&q=80&w=1080',
  image3Alt: 'Medicine delivery',
  image9Src:
    'https://images.unsplash.com/photo-1538389400446-14fdb67e9000?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4OHw&ixlib=rb-4.1.0&q=80&w=1080',
  image11Alt: 'Hero Image',
  action2: undefined,
  action1: undefined,
  image8Src:
    'https://images.unsplash.com/photo-1656229818787-7d5a3b3cab6a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4OHw&ixlib=rb-4.1.0&q=80&w=1080',
  image5Src:
    'https://images.unsplash.com/photo-1569153336922-4d72d778735c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4OXw&ixlib=rb-4.1.0&q=80&w=1080',
  image4Src:
    'https://images.unsplash.com/photo-1493655161922-ef98929de9d8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4OXw&ixlib=rb-4.1.0&q=80&w=1080',
  image10Alt: 'Hero Image',
  image4Alt: 'Mood-detecting mental wellness chatbot',
  heading1: undefined,
  content1: undefined,
  image10Src:
    'https://images.unsplash.com/photo-1662284972119-b83a58515a15?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE5MHw&ixlib=rb-4.1.0&q=80&w=1080',
  image9Alt: 'Hero Image',
  image1Src:
    'https://images.unsplash.com/photo-1594746214383-521df4590053?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE5MXw&ixlib=rb-4.1.0&q=80&w=1080',
}

Hero17.propTypes = {
  image3Src: PropTypes.string,
  image8Alt: PropTypes.string,
  image2Src: PropTypes.string,
  image6Alt: PropTypes.string,
  image11Src: PropTypes.string,
  image5Alt: PropTypes.string,
  image1Alt: PropTypes.string,
  image7Src: PropTypes.string,
  image7Alt: PropTypes.string,
  image12Alt: PropTypes.string,
  image2Alt: PropTypes.string,
  image6Src: PropTypes.string,
  image12Src: PropTypes.string,
  image3Alt: PropTypes.string,
  image9Src: PropTypes.string,
  image11Alt: PropTypes.string,
  action2: PropTypes.element,
  action1: PropTypes.element,
  image8Src: PropTypes.string,
  image5Src: PropTypes.string,
  image4Src: PropTypes.string,
  image10Alt: PropTypes.string,
  image4Alt: PropTypes.string,
  heading1: PropTypes.element,
  content1: PropTypes.element,
  image10Src: PropTypes.string,
  image9Alt: PropTypes.string,
  image1Src: PropTypes.string,
}

export default Hero17
