// faraway united locust-angular/src/app/components/navbar8/navbar8.component.ts
import { Component, Input, ContentChild, TemplateRef } from '@angular/core'

@Component({
  selector: 'app-navbar8',
  templateUrl: 'navbar8.component.html',
  styleUrls: ['navbar8.component.css'],
})
export class Navbar8 {
  @Input()
  linkUrlPage4: string = 'https://www.teleporthq.io'
  @Input()
  link2Url: string = 'https://www.teleporthq.io'
  @ContentChild('page4Description')
  page4Description: TemplateRef<any>
  @Input()
  page1ImageSrc: string =
    'https://images.unsplash.com/photo-1615739137453-bcadd839a913?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4MXw&ixlib=rb-4.1.0&q=80&w=1080'
  @ContentChild('action1')
  action1: TemplateRef<any>
  @Input()
  page2ImageAlt: string = 'Image representing Services page'
  @ContentChild('link2')
  link2: TemplateRef<any>
  @Input()
  linkUrlPage2: string = 'https://www.teleporthq.io'
  @Input()
  logoAlt: string = 'Swasth Saarthi Logo'
  @Input()
  logoSrc: string =
    'https://aheioqhobo.cloudimg.io/v7/_playground-bucket-v2.teleporthq.io_/84ec08e8-34e9-42c7-9445-d2806d156403/fac575ac-7a41-484f-b7ac-875042de11f8?org_if_sml=1&force_format=original'
  @Input()
  page3ImageAlt: string = 'Image representing About Us page'
  @Input()
  linkUrlPage1: string = 'https://www.teleporthq.io'
  @ContentChild('page1')
  page1: TemplateRef<any>
  @ContentChild('link1')
  link1: TemplateRef<any>
  @Input()
  page4ImageSrc: string =
    'https://images.unsplash.com/photo-1446847906594-a81a865cb44e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4Mnw&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  linkUrlPage3: string = 'https://www.teleporthq.io'
  @ContentChild('page4')
  page4: TemplateRef<any>
  @ContentChild('page2')
  page2: TemplateRef<any>
  @ContentChild('link4')
  link4: TemplateRef<any>
  @Input()
  page4ImageAlt: string = 'Image representing Contact page'
  @ContentChild('page1Description')
  page1Description: TemplateRef<any>
  @Input()
  page2ImageSrc: string =
    'https://images.unsplash.com/photo-1666597107756-ef489e9f1f09?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4M3w&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  page3ImageSrc: string =
    'https://images.unsplash.com/photo-1634848577969-bc28ee71ffc1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4NXw&ixlib=rb-4.1.0&q=80&w=1080'
  @ContentChild('page2Description')
  page2Description: TemplateRef<any>
  @ContentChild('link3')
  link3: TemplateRef<any>
  @ContentChild('page3')
  page3: TemplateRef<any>
  @Input()
  link1Url: string = 'https://www.teleporthq.io'
  @ContentChild('page3Description')
  page3Description: TemplateRef<any>
  @Input()
  page1ImageAlt: string = 'Image representing Home page'
  @ContentChild('action2')
  action2: TemplateRef<any>
  @Input()
  link3Url: string = 'https://www.teleporthq.io'
  link5AccordionOpen: boolean = false
  link5DropdownVisible: boolean = false
  constructor() {}
}

<header class="navbar8-container1">
  <header data-thq="thq-navbar" class="navbar8-navbar-interactive">
    <div data-thq="thq-navbar-nav" class="navbar8-desktop-menu">
      <nav class="navbar8-links1">
        <a
          [attr.href]="link1Url"
          class="navbar8-link11 thq-link thq-body-small"
        >
          <ng-container>
            <ng-template #defaultLink1>
              <div><span>/home</span></div>
            </ng-template>
            <ng-container
              *ngTemplateOutlet="link1 ? link1 : defaultLink1"
            ></ng-container>
          </ng-container>
        </a>
        <a [attr.href]="link2Url" class="thq-link thq-body-small">
          <ng-container>
            <ng-template #defaultLink2>
              <div><span>/services</span></div>
            </ng-template>
            <ng-container
              *ngTemplateOutlet="link2 ? link2 : defaultLink2"
            ></ng-container>
          </ng-container>
        </a>
        <a
          [attr.href]="link3Url"
          target="_blank"
          rel="noreferrer noopener"
          class="navbar8-link31 thq-link thq-body-small"
        >
          <ng-container>
            <ng-template #defaultLink3>
              <div><span>/about</span></div>
            </ng-template>
            <ng-container
              *ngTemplateOutlet="link3 ? link3 : defaultLink3"
            ></ng-container>
          </ng-container>
        </a>
        <div
          (click)="link5DropdownVisible = !link5DropdownVisible"
          class="navbar8-link4-dropdown-trigger"
        >
          <span class="thq-link thq-body-small">
            <ng-container>
              <ng-template #defaultLink4>
                <div><span>/contact</span></div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="link4 ? link4 : defaultLink4"
              ></ng-container>
            </ng-container>
          </span>
          <div class="navbar8-icon-container1">
            <div *ngIf="link5DropdownVisible" class="navbar8-container2">
              <svg viewBox="0 0 1024 1024" class="navbar8-icon10">
                <path d="M298 426h428l-214 214z"></path>
              </svg>
            </div>
            <div *ngIf="!link5DropdownVisible" class="navbar8-container3">
              <svg viewBox="0 0 1024 1024" class="navbar8-icon12">
                <path d="M426 726v-428l214 214z"></path>
              </svg>
            </div>
          </div>
        </div>
      </nav>
      <div class="navbar8-buttons1">
        <button class="navbar8-action11 thq-button-animated thq-button-filled">
          <span>
            <ng-container>
              <ng-template #defaultAction1>
                <div><span>Book Appointment</span></div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="action1 ? action1 : defaultAction1"
              ></ng-container>
            </ng-container>
          </span>
        </button>
        <button class="navbar8-action21 thq-button-outline thq-button-animated">
          <span>
            <ng-container>
              <ng-template #defaultAction2>
                <div><span>Learn More</span></div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="action2 ? action2 : defaultAction2"
              ></ng-container>
            </ng-container>
          </span>
        </button>
      </div>
    </div>
    <div data-thq="thq-burger-menu" class="navbar8-burger-menu">
      <svg viewBox="0 0 1024 1024" class="navbar8-icon14">
        <path
          d="M128 554.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667zM128 298.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667zM128 810.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667z"
        ></path>
      </svg>
    </div>
    <div data-thq="thq-mobile-menu" class="navbar8-mobile-menu">
      <div class="navbar8-nav">
        <div class="navbar8-top">
          <img [attr.alt]="logoAlt" [attr.src]="logoSrc" class="navbar8-logo" />
          <div data-thq="thq-close-menu" class="navbar8-close-menu">
            <svg viewBox="0 0 1024 1024" class="navbar8-icon16">
              <path
                d="M810 274l-238 238 238 238-60 60-238-238-238 238-60-60 238-238-238-238 60-60 238 238 238-238z"
              ></path>
            </svg>
          </div>
        </div>
        <nav class="navbar8-links2">
          <a
            [attr.href]="link1Url"
            class="navbar8-link12 thq-link thq-body-small"
          >
            <ng-container>
              <ng-template #defaultLink1>
                <div class="navbar8-fragment14">
                  <span class="navbar8-text18">/home</span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="link1 ? link1 : defaultLink1"
              ></ng-container>
            </ng-container>
          </a>
          <a [attr.href]="link2Url" class="thq-link thq-body-small">
            <ng-container>
              <ng-template #defaultLink2>
                <div class="navbar8-fragment12">
                  <span class="navbar8-text16">/services</span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="link2 ? link2 : defaultLink2"
              ></ng-container>
            </ng-container>
          </a>
          <a
            [attr.href]="link3Url"
            class="navbar8-link32 thq-link thq-body-small"
          >
            <ng-container>
              <ng-template #defaultLink3>
                <div class="navbar8-fragment20">
                  <span class="navbar8-text24">/about</span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="link3 ? link3 : defaultLink3"
              ></ng-container>
            </ng-container>
          </a>
          <div class="navbar8-link4-accordion">
            <div
              (click)="link5AccordionOpen = !link5AccordionOpen"
              class="navbar8-trigger"
            >
              <span class="thq-link thq-body-small">
                <ng-container>
                  <ng-template #defaultLink4>
                    <div class="navbar8-fragment17">
                      <span class="navbar8-text21">/contact</span>
                    </div>
                  </ng-template>
                  <ng-container
                    *ngTemplateOutlet="link4 ? link4 : defaultLink4"
                  ></ng-container>
                </ng-container>
              </span>
              <div class="navbar8-icon-container2">
                <div *ngIf="link5AccordionOpen" class="navbar8-container4">
                  <svg viewBox="0 0 1024 1024" class="navbar8-icon18">
                    <path d="M298 426h428l-214 214z"></path>
                  </svg>
                </div>
                <div *ngIf="!link5AccordionOpen" class="navbar8-container5">
                  <svg viewBox="0 0 1024 1024" class="navbar8-icon20">
                    <path d="M426 726v-428l214 214z"></path>
                  </svg>
                </div>
              </div>
            </div>
            <div *ngIf="link5AccordionOpen" class="navbar8-container6">
              <a [attr.href]="linkUrlPage1">
                <div class="navbar8-menu-item1">
                  <img
                    [attr.alt]="page1ImageAlt"
                    [attr.src]="page1ImageSrc"
                    class="navbar8-page1-image1"
                  />
                  <div class="navbar8-content1">
                    <span class="navbar8-page11 thq-body-large">
                      <ng-container>
                        <ng-template #defaultPage1>
                          <div><span>Home</span></div>
                        </ng-template>
                        <ng-container
                          *ngTemplateOutlet="page1 ? page1 : defaultPage1"
                        ></ng-container>
                      </ng-container>
                    </span>
                    <span class="thq-body-small">
                      <ng-container>
                        <ng-template #defaultPage1Description>
                          <div>
                            <span>
                              Welcome to Swasth Saarthi - Your Health Companion
                            </span>
                          </div>
                        </ng-template>
                        <ng-container
                          *ngTemplateOutlet="page1Description ? page1Description : defaultPage1Description"
                        ></ng-container>
                      </ng-container>
                    </span>
                  </div>
                </div>
              </a>
              <a [attr.href]="linkUrlPage2">
                <div class="navbar8-menu-item2">
                  <img
                    [attr.alt]="page2ImageAlt"
                    [attr.src]="page2ImageSrc"
                    class="navbar8-page2-image1"
                  />
                  <div class="navbar8-content2">
                    <span class="navbar8-page21 thq-body-large">
                      <ng-container>
                        <ng-template #defaultPage2>
                          <div><span>Services</span></div>
                        </ng-template>
                        <ng-container
                          *ngTemplateOutlet="page2 ? page2 : defaultPage2"
                        ></ng-container>
                      </ng-container>
                    </span>
                    <span class="thq-body-small">
                      <ng-container>
                        <ng-template #defaultPage2Description>
                          <div>
                            <span>
                              Explore our range of healthcare services
                            </span>
                          </div>
                        </ng-template>
                        <ng-container
                          *ngTemplateOutlet="page2Description ? page2Description : defaultPage2Description"
                        ></ng-container>
                      </ng-container>
                    </span>
                  </div>
                </div>
              </a>
              <a [attr.href]="linkUrlPage3">
                <div class="navbar8-menu-item3">
                  <img
                    [attr.alt]="page3ImageAlt"
                    [attr.src]="page3ImageSrc"
                    class="navbar8-page3-image1"
                  />
                  <div class="navbar8-content3">
                    <span class="navbar8-page31 thq-body-large">
                      <ng-container>
                        <ng-template #defaultPage3>
                          <div><span>About Us</span></div>
                        </ng-template>
                        <ng-container
                          *ngTemplateOutlet="page3 ? page3 : defaultPage3"
                        ></ng-container>
                      </ng-container>
                    </span>
                    <span class="thq-body-small">
                      <ng-container>
                        <ng-template #defaultPage3Description>
                          <div>
                            <span>Learn more about our mission and team</span>
                          </div>
                        </ng-template>
                        <ng-container
                          *ngTemplateOutlet="page3Description ? page3Description : defaultPage3Description"
                        ></ng-container>
                      </ng-container>
                    </span>
                  </div>
                </div>
              </a>
              <a [attr.href]="linkUrlPage4">
                <div class="navbar8-menu-item4">
                  <img
                    [attr.alt]="page4ImageAlt"
                    [attr.src]="page4ImageSrc"
                    class="navbar8-page4-image1"
                  />
                  <div class="navbar8-content4">
                    <span class="navbar8-page41 thq-body-large">
                      <ng-container>
                        <ng-template #defaultPage4>
                          <div><span>Contact</span></div>
                        </ng-template>
                        <ng-container
                          *ngTemplateOutlet="page4 ? page4 : defaultPage4"
                        ></ng-container>
                      </ng-container>
                    </span>
                    <span class="thq-body-small">
                      <ng-container>
                        <ng-template #defaultPage4Description>
                          <div>
                            <span>Get in touch with us for any inquiries</span>
                          </div>
                        </ng-template>
                        <ng-container
                          *ngTemplateOutlet="page4Description ? page4Description : defaultPage4Description"
                        ></ng-container>
                      </ng-container>
                    </span>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </nav>
        <div class="navbar8-buttons2">
          <button class="thq-button-filled">
            <span>
              <ng-container>
                <ng-template #defaultAction1>
                  <div class="navbar8-fragment11">
                    <span class="navbar8-text15">Book Appointment</span>
                  </div>
                </ng-template>
                <ng-container
                  *ngTemplateOutlet="action1 ? action1 : defaultAction1"
                ></ng-container>
              </ng-container>
            </span>
          </button>
          <button class="thq-button-outline">
            <span>
              <ng-container>
                <ng-template #defaultAction2>
                  <div class="navbar8-fragment23">
                    <span class="navbar8-text27">Learn More</span>
                  </div>
                </ng-template>
                <ng-container
                  *ngTemplateOutlet="action2 ? action2 : defaultAction2"
                ></ng-container>
              </ng-container>
            </span>
          </button>
        </div>
      </div>
      <div class="navbar8-icon-group">
        <svg viewBox="0 0 950.8571428571428 1024" class="thq-icon-x-small">
          <path
            d="M925.714 233.143c-25.143 36.571-56.571 69.143-92.571 95.429 0.571 8 0.571 16 0.571 24 0 244-185.714 525.143-525.143 525.143-104.571 0-201.714-30.286-283.429-82.857 14.857 1.714 29.143 2.286 44.571 2.286 86.286 0 165.714-29.143 229.143-78.857-81.143-1.714-149.143-54.857-172.571-128 11.429 1.714 22.857 2.857 34.857 2.857 16.571 0 33.143-2.286 48.571-6.286-84.571-17.143-148-91.429-148-181.143v-2.286c24.571 13.714 53.143 22.286 83.429 23.429-49.714-33.143-82.286-89.714-82.286-153.714 0-34.286 9.143-65.714 25.143-93.143 90.857 112 227.429 185.143 380.571 193.143-2.857-13.714-4.571-28-4.571-42.286 0-101.714 82.286-184.571 184.571-184.571 53.143 0 101.143 22.286 134.857 58.286 41.714-8 81.714-23.429 117.143-44.571-13.714 42.857-42.857 78.857-81.143 101.714 37.143-4 73.143-14.286 106.286-28.571z"
          ></path></svg
        ><svg viewBox="0 0 877.7142857142857 1024" class="thq-icon-x-small">
          <path
            d="M585.143 512c0-80.571-65.714-146.286-146.286-146.286s-146.286 65.714-146.286 146.286 65.714 146.286 146.286 146.286 146.286-65.714 146.286-146.286zM664 512c0 124.571-100.571 225.143-225.143 225.143s-225.143-100.571-225.143-225.143 100.571-225.143 225.143-225.143 225.143 100.571 225.143 225.143zM725.714 277.714c0 29.143-23.429 52.571-52.571 52.571s-52.571-23.429-52.571-52.571 23.429-52.571 52.571-52.571 52.571 23.429 52.571 52.571zM438.857 152c-64 0-201.143-5.143-258.857 17.714-20 8-34.857 17.714-50.286 33.143s-25.143 30.286-33.143 50.286c-22.857 57.714-17.714 194.857-17.714 258.857s-5.143 201.143 17.714 258.857c8 20 17.714 34.857 33.143 50.286s30.286 25.143 50.286 33.143c57.714 22.857 194.857 17.714 258.857 17.714s201.143 5.143 258.857-17.714c20-8 34.857-17.714 50.286-33.143s25.143-30.286 33.143-50.286c22.857-57.714 17.714-194.857 17.714-258.857s5.143-201.143-17.714-258.857c-8-20-17.714-34.857-33.143-50.286s-30.286-25.143-50.286-33.143c-57.714-22.857-194.857-17.714-258.857-17.714zM877.714 512c0 60.571 0.571 120.571-2.857 181.143-3.429 70.286-19.429 132.571-70.857 184s-113.714 67.429-184 70.857c-60.571 3.429-120.571 2.857-181.143 2.857s-120.571 0.571-181.143-2.857c-70.286-3.429-132.571-19.429-184-70.857s-67.429-113.714-70.857-184c-3.429-60.571-2.857-120.571-2.857-181.143s-0.571-120.571 2.857-181.143c3.429-70.286 19.429-132.571 70.857-184s113.714-67.429 184-70.857c60.571-3.429 120.571-2.857 181.143-2.857s120.571-0.571 181.143 2.857c70.286 3.429 132.571 19.429 184 70.857s67.429 113.714 70.857 184c3.429 60.571 2.857 120.571 2.857 181.143z"
          ></path></svg
        ><svg viewBox="0 0 602.2582857142856 1024" class="thq-icon-small">
          <path
            d="M548 6.857v150.857h-89.714c-70.286 0-83.429 33.714-83.429 82.286v108h167.429l-22.286 169.143h-145.143v433.714h-174.857v-433.714h-145.714v-169.143h145.714v-124.571c0-144.571 88.571-223.429 217.714-223.429 61.714 0 114.857 4.571 130.286 6.857z"
          ></path>
        </svg>
      </div>
    </div>
    <div *ngIf="link5DropdownVisible" class="navbar8-container7 thq-box-shadow">
      <div class="navbar8-link5-menu-list">
        <a [attr.href]="linkUrlPage1">
          <div class="navbar8-menu-item5">
            <img
              [attr.alt]="page1ImageAlt"
              [attr.src]="page1ImageSrc"
              class="navbar8-page1-image2 thq-img-ratio-1-1"
            />
            <div class="navbar8-content5">
              <span class="navbar8-page12 thq-body-large">
                <ng-container>
                  <ng-template #defaultPage1>
                    <div class="navbar8-fragment13">
                      <span class="navbar8-text17">Home</span>
                    </div>
                  </ng-template>
                  <ng-container
                    *ngTemplateOutlet="page1 ? page1 : defaultPage1"
                  ></ng-container>
                </ng-container>
              </span>
              <span class="thq-body-small">
                <ng-container>
                  <ng-template #defaultPage1Description>
                    <div class="navbar8-fragment18">
                      <span class="navbar8-text22">
                        Welcome to Swasth Saarthi - Your Health Companion
                      </span>
                    </div>
                  </ng-template>
                  <ng-container
                    *ngTemplateOutlet="page1Description ? page1Description : defaultPage1Description"
                  ></ng-container>
                </ng-container>
              </span>
            </div>
          </div>
        </a>
        <a [attr.href]="linkUrlPage2">
          <div class="navbar8-menu-item6">
            <img
              [attr.alt]="page2ImageAlt"
              [attr.src]="page2ImageSrc"
              class="navbar8-page2-image2 thq-img-ratio-1-1"
            />
            <div class="navbar8-content6">
              <span class="navbar8-page22 thq-body-large">
                <ng-container>
                  <ng-template #defaultPage2>
                    <div class="navbar8-fragment16">
                      <span class="navbar8-text20">Services</span>
                    </div>
                  </ng-template>
                  <ng-container
                    *ngTemplateOutlet="page2 ? page2 : defaultPage2"
                  ></ng-container>
                </ng-container>
              </span>
              <span class="thq-body-small">
                <ng-container>
                  <ng-template #defaultPage2Description>
                    <div class="navbar8-fragment19">
                      <span class="navbar8-text23">
                        Explore our range of healthcare services
                      </span>
                    </div>
                  </ng-template>
                  <ng-container
                    *ngTemplateOutlet="page2Description ? page2Description : defaultPage2Description"
                  ></ng-container>
                </ng-container>
              </span>
            </div>
          </div>
        </a>
        <a [attr.href]="linkUrlPage3">
          <div class="navbar8-menu-item7">
            <img
              [attr.alt]="page3ImageAlt"
              [attr.src]="page3ImageSrc"
              class="navbar8-page3-image2 thq-img-ratio-1-1"
            />
            <div class="navbar8-content7">
              <span class="navbar8-page32 thq-body-large">
                <ng-container>
                  <ng-template #defaultPage3>
                    <div class="navbar8-fragment21">
                      <span class="navbar8-text25">About Us</span>
                    </div>
                  </ng-template>
                  <ng-container
                    *ngTemplateOutlet="page3 ? page3 : defaultPage3"
                  ></ng-container>
                </ng-container>
              </span>
              <span class="thq-body-small">
                <ng-container>
                  <ng-template #defaultPage3Description>
                    <div class="navbar8-fragment22">
                      <span class="navbar8-text26">
                        Learn more about our mission and team
                      </span>
                    </div>
                  </ng-template>
                  <ng-container
                    *ngTemplateOutlet="page3Description ? page3Description : defaultPage3Description"
                  ></ng-container>
                </ng-container>
              </span>
            </div>
          </div>
        </a>
        <a [attr.href]="linkUrlPage4">
          <div class="navbar8-menu-item8">
            <img
              [attr.alt]="page4ImageAlt"
              [attr.src]="page4ImageSrc"
              class="navbar8-page4-image2 thq-img-ratio-1-1"
            />
            <div class="navbar8-content8">
              <span class="navbar8-page42 thq-body-large">
                <ng-container>
                  <ng-template #defaultPage4>
                    <div class="navbar8-fragment15">
                      <span class="navbar8-text19">Contact</span>
                    </div>
                  </ng-template>
                  <ng-container
                    *ngTemplateOutlet="page4 ? page4 : defaultPage4"
                  ></ng-container>
                </ng-container>
              </span>
              <span class="thq-body-small">
                <ng-container>
                  <ng-template #defaultPage4Description>
                    <div class="navbar8-fragment10">
                      <span class="navbar8-text14">
                        Get in touch with us for any inquiries
                      </span>
                    </div>
                  </ng-template>
                  <ng-container
                    *ngTemplateOutlet="page4Description ? page4Description : defaultPage4Description"
                  ></ng-container>
                </ng-container>
              </span>
            </div>
          </div>
        </a>
      </div>
    </div>
  </header>
  <div
    (click)="link5DropdownVisible = false"
    *ngIf="link5DropdownVisible"
    class="navbar8-container8"
  ></div>
</header>

// faraway united locust-react/src/components/navbar8.js
import React, { useState, Fragment } from 'react'

import PropTypes from 'prop-types'

import './navbar8.css'

const Navbar8 = (props) => {
  const [link5AccordionOpen, setLink5AccordionOpen] = useState(false)
  const [link5DropdownVisible, setLink5DropdownVisible] = useState(false)
  return (
    <header className="navbar8-container1">
      <header data-thq="thq-navbar" className="navbar8-navbar-interactive">
        <div data-thq="thq-navbar-nav" className="navbar8-desktop-menu">
          <nav className="navbar8-links1">
            <a
              href={props.link1Url}
              className="navbar8-link11 thq-link thq-body-small"
            >
              {props.link1 ?? (
                <Fragment>
                  <span className="navbar8-text18">/home</span>
                </Fragment>
              )}
            </a>
            <a href={props.link2Url} className="thq-link thq-body-small">
              {props.link2 ?? (
                <Fragment>
                  <span className="navbar8-text16">/services</span>
                </Fragment>
              )}
            </a>
            <a
              href={props.link3Url}
              target="_blank"
              rel="noreferrer noopener"
              className="navbar8-link31 thq-link thq-body-small"
            >
              {props.link3 ?? (
                <Fragment>
                  <span className="navbar8-text24">/about</span>
                </Fragment>
              )}
            </a>
            <div
              onClick={() => setLink5DropdownVisible(!link5DropdownVisible)}
              className="navbar8-link4-dropdown-trigger"
            >
              <span className="thq-link thq-body-small">
                {props.link4 ?? (
                  <Fragment>
                    <span className="navbar8-text21">/contact</span>
                  </Fragment>
                )}
              </span>
              <div className="navbar8-icon-container1">
                {link5DropdownVisible === true && (
                  <div className="navbar8-container2">
                    <svg viewBox="0 0 1024 1024" className="navbar8-icon10">
                      <path d="M298 426h428l-214 214z"></path>
                    </svg>
                  </div>
                )}
                {link5DropdownVisible === false && (
                  <div className="navbar8-container3">
                    <svg viewBox="0 0 1024 1024" className="navbar8-icon12">
                      <path d="M426 726v-428l214 214z"></path>
                    </svg>
                  </div>
                )}
              </div>
            </div>
          </nav>
          <div className="navbar8-buttons1">
            <button className="navbar8-action11 thq-button-animated thq-button-filled">
              <span>
                {props.action1 ?? (
                  <Fragment>
                    <span className="navbar8-text15">Book Appointment</span>
                  </Fragment>
                )}
              </span>
            </button>
            <button className="navbar8-action21 thq-button-outline thq-button-animated">
              <span>
                {props.action2 ?? (
                  <Fragment>
                    <span className="navbar8-text27">Learn More</span>
                  </Fragment>
                )}
              </span>
            </button>
          </div>
        </div>
        <div data-thq="thq-burger-menu" className="navbar8-burger-menu">
          <svg viewBox="0 0 1024 1024" className="navbar8-icon14">
            <path d="M128 554.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667zM128 298.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667zM128 810.667h768c23.552 0 42.667-19.115 42.667-42.667s-19.115-42.667-42.667-42.667h-768c-23.552 0-42.667 19.115-42.667 42.667s19.115 42.667 42.667 42.667z"></path>
          </svg>
        </div>
        <div data-thq="thq-mobile-menu" className="navbar8-mobile-menu">
          <div className="navbar8-nav">
            <div className="navbar8-top">
              <img
                alt={props.logoAlt}
                src={props.logoSrc}
                className="navbar8-logo"
              />
              <div data-thq="thq-close-menu" className="navbar8-close-menu">
                <svg viewBox="0 0 1024 1024" className="navbar8-icon16">
                  <path d="M810 274l-238 238 238 238-60 60-238-238-238 238-60-60 238-238-238-238 60-60 238 238 238-238z"></path>
                </svg>
              </div>
            </div>
            <nav className="navbar8-links2">
              <a
                href={props.link1Url}
                className="navbar8-link12 thq-link thq-body-small"
              >
                {props.link1 ?? (
                  <Fragment>
                    <span className="navbar8-text18">/home</span>
                  </Fragment>
                )}
              </a>
              <a href={props.link2Url} className="thq-link thq-body-small">
                {props.link2 ?? (
                  <Fragment>
                    <span className="navbar8-text16">/services</span>
                  </Fragment>
                )}
              </a>
              <a
                href={props.link3Url}
                className="navbar8-link32 thq-link thq-body-small"
              >
                {props.link3 ?? (
                  <Fragment>
                    <span className="navbar8-text24">/about</span>
                  </Fragment>
                )}
              </a>
              <div className="navbar8-link4-accordion">
                <div
                  onClick={() => setLink5AccordionOpen(!link5AccordionOpen)}
                  className="navbar8-trigger"
                >
                  <span className="thq-link thq-body-small">
                    {props.link4 ?? (
                      <Fragment>
                        <span className="navbar8-text21">/contact</span>
                      </Fragment>
                    )}
                  </span>
                  <div className="navbar8-icon-container2">
                    {link5AccordionOpen === true && (
                      <div className="navbar8-container4">
                        <svg viewBox="0 0 1024 1024" className="navbar8-icon18">
                          <path d="M298 426h428l-214 214z"></path>
                        </svg>
                      </div>
                    )}
                    {link5AccordionOpen === false && (
                      <div className="navbar8-container5">
                        <svg viewBox="0 0 1024 1024" className="navbar8-icon20">
                          <path d="M426 726v-428l214 214z"></path>
                        </svg>
                      </div>
                    )}
                  </div>
                </div>
                {link5AccordionOpen === true && (
                  <div className="navbar8-container6">
                    <a href={props.linkUrlPage1}>
                      <div className="navbar8-menu-item1">
                        <img
                          alt={props.page1ImageAlt}
                          src={props.page1ImageSrc}
                          className="navbar8-page1-image1"
                        />
                        <div className="navbar8-content1">
                          <span className="navbar8-page11 thq-body-large">
                            {props.page1 ?? (
                              <Fragment>
                                <span className="navbar8-text17">Home</span>
                              </Fragment>
                            )}
                          </span>
                          <span className="thq-body-small">
                            {props.page1Description ?? (
                              <Fragment>
                                <span className="navbar8-text22">
                                  Welcome to Swasth Saarthi - Your Health
                                  Companion
                                </span>
                              </Fragment>
                            )}
                          </span>
                        </div>
                      </div>
                    </a>
                    <a href={props.linkUrlPage2}>
                      <div className="navbar8-menu-item2">
                        <img
                          alt={props.page2ImageAlt}
                          src={props.page2ImageSrc}
                          className="navbar8-page2-image1"
                        />
                        <div className="navbar8-content2">
                          <span className="navbar8-page21 thq-body-large">
                            {props.page2 ?? (
                              <Fragment>
                                <span className="navbar8-text20">Services</span>
                              </Fragment>
                            )}
                          </span>
                          <span className="thq-body-small">
                            {props.page2Description ?? (
                              <Fragment>
                                <span className="navbar8-text23">
                                  Explore our range of healthcare services
                                </span>
                              </Fragment>
                            )}
                          </span>
                        </div>
                      </div>
                    </a>
                    <a href={props.linkUrlPage3}>
                      <div className="navbar8-menu-item3">
                        <img
                          alt={props.page3ImageAlt}
                          src={props.page3ImageSrc}
                          className="navbar8-page3-image1"
                        />
                        <div className="navbar8-content3">
                          <span className="navbar8-page31 thq-body-large">
                            {props.page3 ?? (
                              <Fragment>
                                <span className="navbar8-text25">About Us</span>
                              </Fragment>
                            )}
                          </span>
                          <span className="thq-body-small">
                            {props.page3Description ?? (
                              <Fragment>
                                <span className="navbar8-text26">
                                  Learn more about our mission and team
                                </span>
                              </Fragment>
                            )}
                          </span>
                        </div>
                      </div>
                    </a>
                    <a href={props.linkUrlPage4}>
                      <div className="navbar8-menu-item4">
                        <img
                          alt={props.page4ImageAlt}
                          src={props.page4ImageSrc}
                          className="navbar8-page4-image1"
                        />
                        <div className="navbar8-content4">
                          <span className="navbar8-page41 thq-body-large">
                            {props.page4 ?? (
                              <Fragment>
                                <span className="navbar8-text19">Contact</span>
                              </Fragment>
                            )}
                          </span>
                          <span className="thq-body-small">
                            {props.page4Description ?? (
                              <Fragment>
                                <span className="navbar8-text14">
                                  Get in touch with us for any inquiries
                                </span>
                              </Fragment>
                            )}
                          </span>
                        </div>
                      </div>
                    </a>
                  </div>
                )}
              </div>
            </nav>
            <div className="navbar8-buttons2">
              <button className="thq-button-filled">
                <span>
                  {props.action1 ?? (
                    <Fragment>
                      <span className="navbar8-text15">Book Appointment</span>
                    </Fragment>
                  )}
                </span>
              </button>
              <button className="thq-button-outline">
                <span>
                  {props.action2 ?? (
                    <Fragment>
                      <span className="navbar8-text27">Learn More</span>
                    </Fragment>
                  )}
                </span>
              </button>
            </div>
          </div>
          <div className="navbar8-icon-group">
            <svg
              viewBox="0 0 950.8571428571428 1024"
              className="thq-icon-x-small"
            >
              <path d="M925.714 233.143c-25.143 36.571-56.571 69.143-92.571 95.429 0.571 8 0.571 16 0.571 24 0 244-185.714 525.143-525.143 525.143-104.571 0-201.714-30.286-283.429-82.857 14.857 1.714 29.143 2.286 44.571 2.286 86.286 0 165.714-29.143 229.143-78.857-81.143-1.714-149.143-54.857-172.571-128 11.429 1.714 22.857 2.857 34.857 2.857 16.571 0 33.143-2.286 48.571-6.286-84.571-17.143-148-91.429-148-181.143v-2.286c24.571 13.714 53.143 22.286 83.429 23.429-49.714-33.143-82.286-89.714-82.286-153.714 0-34.286 9.143-65.714 25.143-93.143 90.857 112 227.429 185.143 380.571 193.143-2.857-13.714-4.571-28-4.571-42.286 0-101.714 82.286-184.571 184.571-184.571 53.143 0 101.143 22.286 134.857 58.286 41.714-8 81.714-23.429 117.143-44.571-13.714 42.857-42.857 78.857-81.143 101.714 37.143-4 73.143-14.286 106.286-28.571z"></path>
            </svg>
            <svg
              viewBox="0 0 877.7142857142857 1024"
              className="thq-icon-x-small"
            >
              <path d="M585.143 512c0-80.571-65.714-146.286-146.286-146.286s-146.286 65.714-146.286 146.286 65.714 146.286 146.286 146.286 146.286-65.714 146.286-146.286zM664 512c0 124.571-100.571 225.143-225.143 225.143s-225.143-100.571-225.143-225.143 100.571-225.143 225.143-225.143 225.143 100.571 225.143 225.143zM725.714 277.714c0 29.143-23.429 52.571-52.571 52.571s-52.571-23.429-52.571-52.571 23.429-52.571 52.571-52.571 52.571 23.429 52.571 52.571zM438.857 152c-64 0-201.143-5.143-258.857 17.714-20 8-34.857 17.714-50.286 33.143s-25.143 30.286-33.143 50.286c-22.857 57.714-17.714 194.857-17.714 258.857s-5.143 201.143 17.714 258.857c8 20 17.714 34.857 33.143 50.286s30.286 25.143 50.286 33.143c57.714 22.857 194.857 17.714 258.857 17.714s201.143 5.143 258.857-17.714c20-8 34.857-17.714 50.286-33.143s25.143-30.286 33.143-50.286c22.857-57.714 17.714-194.857 17.714-258.857s5.143-201.143-17.714-258.857c-8-20-17.714-34.857-33.143-50.286s-30.286-25.143-50.286-33.143c-57.714-22.857-194.857-17.714-258.857-17.714zM877.714 512c0 60.571 0.571 120.571-2.857 181.143-3.429 70.286-19.429 132.571-70.857 184s-113.714 67.429-184 70.857c-60.571 3.429-120.571 2.857-181.143 2.857s-120.571 0.571-181.143-2.857c-70.286-3.429-132.571-19.429-184-70.857s-67.429-113.714-70.857-184c-3.429-60.571-2.857-120.571-2.857-181.143s-0.571-120.571 2.857-181.143c3.429-70.286 19.429-132.571 70.857-184s113.714-67.429 184-70.857c60.571-3.429 120.571-2.857 181.143-2.857s120.571-0.571 181.143 2.857c70.286 3.429 132.571 19.429 184 70.857s67.429 113.714 70.857 184c3.429 60.571 2.857 120.571 2.857 181.143z"></path>
            </svg>
            <svg
              viewBox="0 0 602.2582857142856 1024"
              className="thq-icon-small"
            >
              <path d="M548 6.857v150.857h-89.714c-70.286 0-83.429 33.714-83.429 82.286v108h167.429l-22.286 169.143h-145.143v433.714h-174.857v-433.714h-145.714v-169.143h145.714v-124.571c0-144.571 88.571-223.429 217.714-223.429 61.714 0 114.857 4.571 130.286 6.857z"></path>
            </svg>
          </div>
        </div>
        {link5DropdownVisible === true && (
          <div className="navbar8-container7 thq-box-shadow">
            <div className="navbar8-link5-menu-list">
              <a href={props.linkUrlPage1}>
                <div className="navbar8-menu-item5">
                  <img
                    alt={props.page1ImageAlt}
                    src={props.page1ImageSrc}
                    className="navbar8-page1-image2 thq-img-ratio-1-1"
                  />
                  <div className="navbar8-content5">
                    <span className="navbar8-page12 thq-body-large">
                      {props.page1 ?? (
                        <Fragment>
                          <span className="navbar8-text17">Home</span>
                        </Fragment>
                      )}
                    </span>
                    <span className="thq-body-small">
                      {props.page1Description ?? (
                        <Fragment>
                          <span className="navbar8-text22">
                            Welcome to Swasth Saarthi - Your Health Companion
                          </span>
                        </Fragment>
                      )}
                    </span>
                  </div>
                </div>
              </a>
              <a href={props.linkUrlPage2}>
                <div className="navbar8-menu-item6">
                  <img
                    alt={props.page2ImageAlt}
                    src={props.page2ImageSrc}
                    className="navbar8-page2-image2 thq-img-ratio-1-1"
                  />
                  <div className="navbar8-content6">
                    <span className="navbar8-page22 thq-body-large">
                      {props.page2 ?? (
                        <Fragment>
                          <span className="navbar8-text20">Services</span>
                        </Fragment>
                      )}
                    </span>
                    <span className="thq-body-small">
                      {props.page2Description ?? (
                        <Fragment>
                          <span className="navbar8-text23">
                            Explore our range of healthcare services
                          </span>
                        </Fragment>
                      )}
                    </span>
                  </div>
                </div>
              </a>
              <a href={props.linkUrlPage3}>
                <div className="navbar8-menu-item7">
                  <img
                    alt={props.page3ImageAlt}
                    src={props.page3ImageSrc}
                    className="navbar8-page3-image2 thq-img-ratio-1-1"
                  />
                  <div className="navbar8-content7">
                    <span className="navbar8-page32 thq-body-large">
                      {props.page3 ?? (
                        <Fragment>
                          <span className="navbar8-text25">About Us</span>
                        </Fragment>
                      )}
                    </span>
                    <span className="thq-body-small">
                      {props.page3Description ?? (
                        <Fragment>
                          <span className="navbar8-text26">
                            Learn more about our mission and team
                          </span>
                        </Fragment>
                      )}
                    </span>
                  </div>
                </div>
              </a>
              <a href={props.linkUrlPage4}>
                <div className="navbar8-menu-item8">
                  <img
                    alt={props.page4ImageAlt}
                    src={props.page4ImageSrc}
                    className="navbar8-page4-image2 thq-img-ratio-1-1"
                  />
                  <div className="navbar8-content8">
                    <span className="navbar8-page42 thq-body-large">
                      {props.page4 ?? (
                        <Fragment>
                          <span className="navbar8-text19">Contact</span>
                        </Fragment>
                      )}
                    </span>
                    <span className="thq-body-small">
                      {props.page4Description ?? (
                        <Fragment>
                          <span className="navbar8-text14">
                            Get in touch with us for any inquiries
                          </span>
                        </Fragment>
                      )}
                    </span>
                  </div>
                </div>
              </a>
            </div>
          </div>
        )}
      </header>
      {link5DropdownVisible === true && (
        <div
          onClick={() => setLink5DropdownVisible(false)}
          className="navbar8-container8"
        ></div>
      )}
    </header>
  )
}

Navbar8.defaultProps = {
  linkUrlPage4: 'https://www.teleporthq.io',
  link2Url: 'https://www.teleporthq.io',
  page4Description: undefined,
  page1ImageSrc:
    'https://images.unsplash.com/photo-1615739137453-bcadd839a913?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4MXw&ixlib=rb-4.1.0&q=80&w=1080',
  action1: undefined,
  page2ImageAlt: 'Image representing Services page',
  link2: undefined,
  linkUrlPage2: 'https://www.teleporthq.io',
  logoAlt: 'Swasth Saarthi Logo',
  logoSrc:
    'https://aheioqhobo.cloudimg.io/v7/_playground-bucket-v2.teleporthq.io_/84ec08e8-34e9-42c7-9445-d2806d156403/fac575ac-7a41-484f-b7ac-875042de11f8?org_if_sml=1&force_format=original',
  page3ImageAlt: 'Image representing About Us page',
  linkUrlPage1: 'https://www.teleporthq.io',
  page1: undefined,
  link1: undefined,
  page4ImageSrc:
    'https://images.unsplash.com/photo-1446847906594-a81a865cb44e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4Mnw&ixlib=rb-4.1.0&q=80&w=1080',
  linkUrlPage3: 'https://www.teleporthq.io',
  page4: undefined,
  page2: undefined,
  link4: undefined,
  page4ImageAlt: 'Image representing Contact page',
  page1Description: undefined,
  page2ImageSrc:
    'https://images.unsplash.com/photo-1666597107756-ef489e9f1f09?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4M3w&ixlib=rb-4.1.0&q=80&w=1080',
  page3ImageSrc:
    'https://images.unsplash.com/photo-1634848577969-bc28ee71ffc1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4NXw&ixlib=rb-4.1.0&q=80&w=1080',
  page2Description: undefined,
  link3: undefined,
  page3: undefined,
  link1Url: 'https://www.teleporthq.io',
  page3Description: undefined,
  page1ImageAlt: 'Image representing Home page',
  action2: undefined,
  link3Url: 'https://www.teleporthq.io',
}

Navbar8.propTypes = {
  linkUrlPage4: PropTypes.string,
  link2Url: PropTypes.string,
  page4Description: PropTypes.element,
  page1ImageSrc: PropTypes.string,
  action1: PropTypes.element,
  page2ImageAlt: PropTypes.string,
  link2: PropTypes.element,
  linkUrlPage2: PropTypes.string,
  logoAlt: PropTypes.string,
  logoSrc: PropTypes.string,
  page3ImageAlt: PropTypes.string,
  linkUrlPage1: PropTypes.string,
  page1: PropTypes.element,
  link1: PropTypes.element,
  page4ImageSrc: PropTypes.string,
  linkUrlPage3: PropTypes.string,
  page4: PropTypes.element,
  page2: PropTypes.element,
  link4: PropTypes.element,
  page4ImageAlt: PropTypes.string,
  page1Description: PropTypes.element,
  page2ImageSrc: PropTypes.string,
  page3ImageSrc: PropTypes.string,
  page2Description: PropTypes.element,
  link3: PropTypes.element,
  page3: PropTypes.element,
  link1Url: PropTypes.string,
  page3Description: PropTypes.element,
  page1ImageAlt: PropTypes.string,
  action2: PropTypes.element,
  link3Url: PropTypes.string,
}

export default Navbar8
