// faraway united locust-react/src/components/features24.js
import React, { useState, Fragment } from 'react'

import PropTypes from 'prop-types'

import './features24.css'

const Features24 = (props) => {
  const [activeTab, setActiveTab] = useState(0)
  return (
    <div className="thq-section-padding">
      <div className="features24-container2 thq-section-max-width">
        <div className="features24-image-container">
          {activeTab === 0 && (
            <img
              alt={props.feature1ImgAlt}
              src={props.feature1ImgSrc}
              className="features24-image1 thq-img-ratio-16-9"
            />
          )}
          {activeTab === 1 && (
            <img
              alt={props.feature2ImgAlt}
              src={props.feature2ImgSrc}
              className="features24-image2 thq-img-ratio-16-9"
            />
          )}
          {activeTab === 2 && (
            <img
              alt={props.feature3ImgAlt}
              src={props.feature3ImgSrc}
              className="features24-image3 thq-img-ratio-16-9"
            />
          )}
        </div>
        <div className="features24-tabs-menu">
          <div
            onClick={() => setActiveTab(0)}
            className="features24-tab-horizontal1"
          >
            <div className="features24-divider-container1">
              {activeTab === 0 && <div className="features24-container3"></div>}
            </div>
            <div className="features24-content1">
              <h2 className="thq-heading-2">
                {props.feature1Title ?? (
                  <Fragment>
                    <span className="features24-text4">AI Symptom Checker</span>
                  </Fragment>
                )}
              </h2>
              <span className="thq-body-small">
                {props.feature1Description ?? (
                  <Fragment>
                    <span className="features24-text5">
                      AI-powered symptom checker for accurate health assessments
                    </span>
                  </Fragment>
                )}
              </span>
            </div>
          </div>
          <div
            onClick={() => setActiveTab(1)}
            className="features24-tab-horizontal2"
          >
            <div className="features24-divider-container2">
              {activeTab === 1 && <div className="features24-container4"></div>}
            </div>
            <div className="features24-content2">
              <h2 className="thq-heading-2">
                {props.feature2Title ?? (
                  <Fragment>
                    <span className="features24-text6">
                      Telemedicine Consultations
                    </span>
                  </Fragment>
                )}
              </h2>
              <span className="thq-body-small">
                {props.feature2Description ?? (
                  <Fragment>
                    <span className="features24-text3">
                      Telemedicine consultations
                    </span>
                  </Fragment>
                )}
              </span>
            </div>
          </div>
          <div
            onClick={() => setActiveTab(2)}
            className="features24-tab-horizontal3"
          >
            <div className="features24-divider-container3">
              {activeTab === 2 && <div className="features24-container5"></div>}
            </div>
            <div className="features24-content3">
              <h2 className="thq-heading-2">
                {props.feature3Title ?? (
                  <Fragment>
                    <span className="features24-text2">Medicine Delivery</span>
                  </Fragment>
                )}
              </h2>
              <span className="thq-body-small">
                {props.feature3Description ?? (
                  <Fragment>
                    <span className="features24-text1">Medicine delivery</span>
                  </Fragment>
                )}
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

Features24.defaultProps = {
  feature1ImgAlt: 'AI symptom checker',
  feature3Description: undefined,
  feature3Title: undefined,
  feature3ImgSrc:
    'https://images.unsplash.com/photo-1698516923132-b0236bc8f3ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4MXw&ixlib=rb-4.1.0&q=80&w=1080',
  feature1ImgSrc:
    'https://images.unsplash.com/photo-1510391947036-00d38cc22ad8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4MXw&ixlib=rb-4.1.0&q=80&w=1080',
  feature2Description: undefined,
  feature1Title: undefined,
  feature3ImgAlt: 'Medicine delivery',
  feature1Description: undefined,
  feature2ImgSrc:
    'https://images.unsplash.com/photo-1666330404750-061d4858593b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4Mnw&ixlib=rb-4.1.0&q=80&w=1080',
  feature2ImgAlt: 'Telemedicine consultations',
  feature2Title: undefined,
}

Features24.propTypes = {
  feature1ImgAlt: PropTypes.string,
  feature3Description: PropTypes.element,
  feature3Title: PropTypes.element,
  feature3ImgSrc: PropTypes.string,
  feature1ImgSrc: PropTypes.string,
  feature2Description: PropTypes.element,
  feature1Title: PropTypes.element,
  feature3ImgAlt: PropTypes.string,
  feature1Description: PropTypes.element,
  feature2ImgSrc: PropTypes.string,
  feature2ImgAlt: PropTypes.string,
  feature2Title: PropTypes.element,
}

export default Features24

// faraway united locust-angular/src/app/components/features24/features24.component.ts
import { Component, Input, ContentChild, TemplateRef } from '@angular/core'

@Component({
  selector: 'app-features24',
  templateUrl: 'features24.component.html',
  styleUrls: ['features24.component.css'],
})
export class Features24 {
  @Input()
  feature1ImgAlt: string = 'AI symptom checker'
  @ContentChild('feature3Description')
  feature3Description: TemplateRef<any>
  @ContentChild('feature3Title')
  feature3Title: TemplateRef<any>
  @Input()
  feature3ImgSrc: string =
    'https://images.unsplash.com/photo-1698516923132-b0236bc8f3ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4MXw&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  feature1ImgSrc: string =
    'https://images.unsplash.com/photo-1510391947036-00d38cc22ad8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4MXw&ixlib=rb-4.1.0&q=80&w=1080'
  @ContentChild('feature2Description')
  feature2Description: TemplateRef<any>
  @ContentChild('feature1Title')
  feature1Title: TemplateRef<any>
  @Input()
  feature3ImgAlt: string = 'Medicine delivery'
  @ContentChild('feature1Description')
  feature1Description: TemplateRef<any>
  @Input()
  feature2ImgSrc: string =
    'https://images.unsplash.com/photo-1666330404750-061d4858593b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4Mnw&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  feature2ImgAlt: string = 'Telemedicine consultations'
  @ContentChild('feature2Title')
  feature2Title: TemplateRef<any>
  activeTab: number = 0
  constructor() {}
}

<div class="thq-section-padding">
  <div class="features24-container2 thq-section-max-width">
    <div class="features24-image-container">
      <img
        [attr.alt]="feature1ImgAlt"
        [attr.src]="feature1ImgSrc"
        *ngIf="activeTab = 0"
        class="features24-image1 thq-img-ratio-16-9"
      />
      <img
        [attr.alt]="feature2ImgAlt"
        [attr.src]="feature2ImgSrc"
        *ngIf="activeTab = 1"
        class="features24-image2 thq-img-ratio-16-9"
      />
      <img
        [attr.alt]="feature3ImgAlt"
        [attr.src]="feature3ImgSrc"
        *ngIf="activeTab = 2"
        class="features24-image3 thq-img-ratio-16-9"
      />
    </div>
    <div class="features24-tabs-menu">
      <div (click)="activeTab = 0" class="features24-tab-horizontal1">
        <div class="features24-divider-container1">
          <div *ngIf="activeTab = 0" class="features24-container3"></div>
        </div>
        <div class="features24-content1">
          <h2 class="thq-heading-2">
            <ng-container>
              <ng-template #defaultFeature1Title>
                <div class="features24-fragment4">
                  <span class="features24-text4">AI Symptom Checker</span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="feature1Title ? feature1Title : defaultFeature1Title"
              ></ng-container>
            </ng-container>
          </h2>
          <span class="thq-body-small">
            <ng-container>
              <ng-template #defaultFeature1Description>
                <div class="features24-fragment5">
                  <span class="features24-text5">
                    AI-powered symptom checker for accurate health assessments
                  </span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="feature1Description ? feature1Description : defaultFeature1Description"
              ></ng-container>
            </ng-container>
          </span>
        </div>
      </div>
      <div (click)="activeTab = 1" class="features24-tab-horizontal2">
        <div class="features24-divider-container2">
          <div *ngIf="activeTab = 1" class="features24-container4"></div>
        </div>
        <div class="features24-content2">
          <h2 class="thq-heading-2">
            <ng-container>
              <ng-template #defaultFeature2Title>
                <div class="features24-fragment6">
                  <span class="features24-text6">
                    Telemedicine Consultations
                  </span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="feature2Title ? feature2Title : defaultFeature2Title"
              ></ng-container>
            </ng-container>
          </h2>
          <span class="thq-body-small">
            <ng-container>
              <ng-template #defaultFeature2Description>
                <div class="features24-fragment3">
                  <span class="features24-text3">
                    Telemedicine consultations
                  </span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="feature2Description ? feature2Description : defaultFeature2Description"
              ></ng-container>
            </ng-container>
          </span>
        </div>
      </div>
      <div (click)="activeTab = 2" class="features24-tab-horizontal3">
        <div class="features24-divider-container3">
          <div *ngIf="activeTab = 2" class="features24-container5"></div>
        </div>
        <div class="features24-content3">
          <h2 class="thq-heading-2">
            <ng-container>
              <ng-template #defaultFeature3Title>
                <div class="features24-fragment2">
                  <span class="features24-text2">Medicine Delivery</span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="feature3Title ? feature3Title : defaultFeature3Title"
              ></ng-container>
            </ng-container>
          </h2>
          <span class="thq-body-small">
            <ng-container>
              <ng-template #defaultFeature3Description>
                <div class="features24-fragment1">
                  <span class="features24-text1">Medicine delivery</span>
                </div>
              </ng-template>
              <ng-container
                *ngTemplateOutlet="feature3Description ? feature3Description : defaultFeature3Description"
              ></ng-container>
            </ng-container>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>
