// faraway united locust-react/src/components/testimonial17.js
import React, { Fragment } from 'react'

import PropTypes from 'prop-types'

import './testimonial17.css'

const Testimonial17 = (props) => {
  return (
    <div className="thq-section-padding">
      <div className="testimonial17-max-width thq-section-max-width">
        <div className="testimonial17-container10">
          <h2 className="thq-heading-2">
            {props.heading1 ?? (
              <Fragment>
                <span className="testimonial17-text35">Testimonials</span>
              </Fragment>
            )}
          </h2>
          <span className="testimonial17-text11 thq-body-small">
            {props.content1 ?? (
              <Fragment>
                <span className="testimonial17-text32">
                  Swasth Saarthi has been a lifesaver for me and my family. I
                  can now consult with doctors without traveling long distances,
                  saving time and money. The AI symptom checker is incredibly
                  accurate, and the medicine delivery service is a blessing.
                </span>
              </Fragment>
            )}
          </span>
        </div>
        <div className="thq-grid-2">
          <div className="thq-animated-card-bg-2">
            <div className="thq-animated-card-bg-1">
              <div
                data-animated="true"
                className="thq-card testimonial17-card1"
              >
                <div className="testimonial17-container12">
                  <img
                    alt={props.author1Alt}
                    src={props.author1Src}
                    className="testimonial17-image1"
                  />
                  <div className="testimonial17-container13">
                    <strong className="thq-body-large">
                      {props.author1Name ?? (
                        <Fragment>
                          <span className="testimonial17-text26">
                            Rajesh Patel
                          </span>
                        </Fragment>
                      )}
                    </strong>
                    <span className="thq-body-small">
                      {props.author1Position ?? (
                        <Fragment>
                          <span className="testimonial17-text25">Farmer</span>
                        </Fragment>
                      )}
                    </span>
                  </div>
                </div>
                <span className="testimonial17-text14 thq-body-small">
                  {props.review1 ?? (
                    <Fragment>
                      <span className="testimonial17-text34">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        Suspendisse varius enim in eros elementum tristique.
                        Duis cursus, mi quis viverra ornare, eros dolor interdum
                        nulla.
                      </span>
                    </Fragment>
                  )}
                </span>
              </div>
            </div>
          </div>
          <div className="thq-animated-card-bg-2">
            <div className="thq-animated-card-bg-1">
              <div
                data-animated="true"
                className="thq-card testimonial17-card2"
              >
                <div className="testimonial17-container14">
                  <img
                    alt={props.author2Alt}
                    src={props.author2Src}
                    className="testimonial17-image2"
                  />
                  <div className="testimonial17-container15">
                    <strong className="thq-body-large">
                      {props.author2Name ?? (
                        <Fragment>
                          <span className="testimonial17-text29">
                            Sunita Devi
                          </span>
                        </Fragment>
                      )}
                    </strong>
                    <span className="thq-body-small">
                      {props.author2Position ?? (
                        <Fragment>
                          <span className="testimonial17-text24">Teacher</span>
                        </Fragment>
                      )}
                    </span>
                  </div>
                </div>
                <span className="testimonial17-text17 thq-body-small">
                  {props.review2 ?? (
                    <Fragment>
                      <span className="testimonial17-text28">
                        As a teacher in a remote village, accessing healthcare
                        was always a challenge. Swasth Saarthi has made it
                        convenient for me to seek medical advice and get
                        prescriptions delivered to my doorstep. The mental
                        wellness chatbot has also helped me manage stress
                        better.
                      </span>
                    </Fragment>
                  )}
                </span>
              </div>
            </div>
          </div>
          <div className="thq-animated-card-bg-2">
            <div className="thq-animated-card-bg-1">
              <div
                data-animated="true"
                className="thq-card testimonial17-card3"
              >
                <div className="testimonial17-container16">
                  <img
                    alt={props.author3Alt}
                    src={props.author3Src}
                    className="testimonial17-image3"
                  />
                  <div className="testimonial17-container17">
                    <strong className="thq-body-large">
                      {props.author3Name ?? (
                        <Fragment>
                          <span className="testimonial17-text27">
                            Amit Kumar
                          </span>
                        </Fragment>
                      )}
                    </strong>
                    <span className="thq-body-small">
                      {props.author3Position ?? (
                        <Fragment>
                          <span className="testimonial17-text33">
                            Local Shop Owner
                          </span>
                        </Fragment>
                      )}
                    </span>
                  </div>
                </div>
                <span className="testimonial17-text20 thq-body-small">
                  {props.review3 ?? (
                    <Fragment>
                      <span className="testimonial17-text36">
                        I never thought I could receive quality healthcare
                        services from the comfort of my shop until I discovered
                        Swasth Saarthi. The telemedicine consultations have been
                        prompt and effective, and the multi-language support is
                        a game-changer for our community.
                      </span>
                    </Fragment>
                  )}
                </span>
              </div>
            </div>
          </div>
          <div className="thq-animated-card-bg-2">
            <div className="thq-animated-card-bg-1">
              <div
                data-animated="true"
                className="thq-card testimonial17-card4"
              >
                <div className="testimonial17-container18">
                  <img
                    alt={props.author4Alt}
                    src={props.author4Src}
                    className="testimonial17-image4"
                  />
                  <div className="testimonial17-container19">
                    <strong className="thq-body-large">
                      {props.author4Name ?? (
                        <Fragment>
                          <span className="testimonial17-text31">
                            Priya Singh
                          </span>
                        </Fragment>
                      )}
                    </strong>
                    <span className="thq-body-small">
                      {props.author4Position ?? (
                        <Fragment>
                          <span className="testimonial17-text30">
                            Social Worker
                          </span>
                        </Fragment>
                      )}
                    </span>
                  </div>
                </div>
                <span className="testimonial17-text23 thq-body-small">
                  {props.review4 ?? (
                    <Fragment>
                      <span className="testimonial17-text37">
                        Working with marginalized communities, I have seen
                        firsthand the impact of Swasth Saarthi in bridging the
                        healthcare gap. The platform&apos;s integration with
                        government programs ensures that even the most
                        vulnerable populations have access to essential medical
                        services.
                      </span>
                    </Fragment>
                  )}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

Testimonial17.defaultProps = {
  author2Position: undefined,
  author1Position: undefined,
  author3Alt: 'Image of Amit Kumar',
  author1Name: undefined,
  author1Src:
    'https://images.unsplash.com/photo-1587723958656-ee042cc565a1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4MXw&ixlib=rb-4.1.0&q=80&w=1080',
  author3Name: undefined,
  review2: undefined,
  author2Name: undefined,
  author4Position: undefined,
  author4Name: undefined,
  author4Src:
    'https://images.unsplash.com/photo-1558898479-33c0057a5d12?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4MXw&ixlib=rb-4.1.0&q=80&w=1080',
  author1Alt: 'Image of Rajesh Patel',
  author2Src:
    'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4MXw&ixlib=rb-4.1.0&q=80&w=1080',
  author3Src:
    'https://images.unsplash.com/photo-1518305860742-0d7119d4567f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4Mnw&ixlib=rb-4.1.0&q=80&w=1080',
  author2Alt: 'Image of Sunita Devi',
  author4Alt: 'Image of Priya Singh',
  content1: undefined,
  author3Position: undefined,
  review1: undefined,
  heading1: undefined,
  review3: undefined,
  review4: undefined,
}

Testimonial17.propTypes = {
  author2Position: PropTypes.element,
  author1Position: PropTypes.element,
  author3Alt: PropTypes.string,
  author1Name: PropTypes.element,
  author1Src: PropTypes.string,
  author3Name: PropTypes.element,
  review2: PropTypes.element,
  author2Name: PropTypes.element,
  author4Position: PropTypes.element,
  author4Name: PropTypes.element,
  author4Src: PropTypes.string,
  author1Alt: PropTypes.string,
  author2Src: PropTypes.string,
  author3Src: PropTypes.string,
  author2Alt: PropTypes.string,
  author4Alt: PropTypes.string,
  content1: PropTypes.element,
  author3Position: PropTypes.element,
  review1: PropTypes.element,
  heading1: PropTypes.element,
  review3: PropTypes.element,
  review4: PropTypes.element,
}

export default Testimonial17

// faraway united locust-angular/src/app/components/testimonial17/testimonial17.component.ts
import { Component, Input, ContentChild, TemplateRef } from '@angular/core'

@Component({
  selector: 'app-testimonial17',
  templateUrl: 'testimonial17.component.html',
  styleUrls: ['testimonial17.component.css'],
})
export class Testimonial17 {
  @ContentChild('author2Position')
  author2Position: TemplateRef<any>
  @ContentChild('author1Position')
  author1Position: TemplateRef<any>
  @Input()
  author3Alt: string = 'Image of Amit Kumar'
  @ContentChild('author1Name')
  author1Name: TemplateRef<any>
  @Input()
  author1Src: string =
    'https://images.unsplash.com/photo-1587723958656-ee042cc565a1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4MXw&ixlib=rb-4.1.0&q=80&w=1080'
  @ContentChild('author3Name')
  author3Name: TemplateRef<any>
  @ContentChild('review2')
  review2: TemplateRef<any>
  @ContentChild('author2Name')
  author2Name: TemplateRef<any>
  @ContentChild('author4Position')
  author4Position: TemplateRef<any>
  @ContentChild('author4Name')
  author4Name: TemplateRef<any>
  @Input()
  author4Src: string =
    'https://images.unsplash.com/photo-1558898479-33c0057a5d12?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4MXw&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  author1Alt: string = 'Image of Rajesh Patel'
  @Input()
  author2Src: string =
    'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4MXw&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  author3Src: string =
    'https://images.unsplash.com/photo-1518305860742-0d7119d4567f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w5MTMyMXwwfDF8cmFuZG9tfHx8fHx8fHx8MTc1NTAxNDE4Mnw&ixlib=rb-4.1.0&q=80&w=1080'
  @Input()
  author2Alt: string = 'Image of Sunita Devi'
  @Input()
  author4Alt: string = 'Image of Priya Singh'
  @ContentChild('content1')
  content1: TemplateRef<any>
  @ContentChild('author3Position')
  author3Position: TemplateRef<any>
  @ContentChild('review1')
  review1: TemplateRef<any>
  @ContentChild('heading1')
  heading1: TemplateRef<any>
  @ContentChild('review3')
  review3: TemplateRef<any>
  @ContentChild('review4')
  review4: TemplateRef<any>
  constructor() {}
}

<div class="thq-section-padding">
  <div class="testimonial17-max-width thq-section-max-width">
    <div class="testimonial17-container10">
      <h2 class="thq-heading-2">
        <ng-container>
          <ng-template #defaultHeading1>
            <div class="testimonial17-fragment21">
              <span class="testimonial17-text35">Testimonials</span>
            </div>
          </ng-template>
          <ng-container
            *ngTemplateOutlet="heading1 ? heading1 : defaultHeading1"
          ></ng-container>
        </ng-container>
      </h2>
      <span class="testimonial17-text11 thq-body-small">
        <ng-container>
          <ng-template #defaultContent1>
            <div class="testimonial17-fragment18">
              <span class="testimonial17-text32">
                Swasth Saarthi has been a lifesaver for me and my family. I can
                now consult with doctors without traveling long distances,
                saving time and money. The AI symptom checker is incredibly
                accurate, and the medicine delivery service is a blessing.
              </span>
            </div>
          </ng-template>
          <ng-container
            *ngTemplateOutlet="content1 ? content1 : defaultContent1"
          ></ng-container>
        </ng-container>
      </span>
    </div>
    <div class="thq-grid-2">
      <div class="thq-animated-card-bg-2">
        <div class="thq-animated-card-bg-1">
          <div data-animated="true" class="thq-card testimonial17-card1">
            <div class="testimonial17-container12">
              <img
                [attr.alt]="author1Alt"
                [attr.src]="author1Src"
                class="testimonial17-image1"
              />
              <div class="testimonial17-container13">
                <strong class="thq-body-large">
                  <ng-container>
                    <ng-template #defaultAuthor1Name>
                      <div class="testimonial17-fragment12">
                        <span class="testimonial17-text26">Rajesh Patel</span>
                      </div>
                    </ng-template>
                    <ng-container
                      *ngTemplateOutlet="author1Name ? author1Name : defaultAuthor1Name"
                    ></ng-container>
                  </ng-container>
                </strong>
                <span class="thq-body-small">
                  <ng-container>
                    <ng-template #defaultAuthor1Position>
                      <div class="testimonial17-fragment11">
                        <span class="testimonial17-text25">Farmer</span>
                      </div>
                    </ng-template>
                    <ng-container
                      *ngTemplateOutlet="author1Position ? author1Position : defaultAuthor1Position"
                    ></ng-container>
                  </ng-container>
                </span>
              </div>
            </div>
            <span class="testimonial17-text14 thq-body-small">
              <ng-container>
                <ng-template #defaultReview1>
                  <div class="testimonial17-fragment20">
                    <span class="testimonial17-text34">
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                      Suspendisse varius enim in eros elementum tristique. Duis
                      cursus, mi quis viverra ornare, eros dolor interdum nulla.
                    </span>
                  </div>
                </ng-template>
                <ng-container
                  *ngTemplateOutlet="review1 ? review1 : defaultReview1"
                ></ng-container>
              </ng-container>
            </span>
          </div>
        </div>
      </div>
      <div class="thq-animated-card-bg-2">
        <div class="thq-animated-card-bg-1">
          <div data-animated="true" class="thq-card testimonial17-card2">
            <div class="testimonial17-container14">
              <img
                [attr.alt]="author2Alt"
                [attr.src]="author2Src"
                class="testimonial17-image2"
              />
              <div class="testimonial17-container15">
                <strong class="thq-body-large">
                  <ng-container>
                    <ng-template #defaultAuthor2Name>
                      <div class="testimonial17-fragment15">
                        <span class="testimonial17-text29">Sunita Devi</span>
                      </div>
                    </ng-template>
                    <ng-container
                      *ngTemplateOutlet="author2Name ? author2Name : defaultAuthor2Name"
                    ></ng-container>
                  </ng-container>
                </strong>
                <span class="thq-body-small">
                  <ng-container>
                    <ng-template #defaultAuthor2Position>
                      <div class="testimonial17-fragment10">
                        <span class="testimonial17-text24">Teacher</span>
                      </div>
                    </ng-template>
                    <ng-container
                      *ngTemplateOutlet="author2Position ? author2Position : defaultAuthor2Position"
                    ></ng-container>
                  </ng-container>
                </span>
              </div>
            </div>
            <span class="testimonial17-text17 thq-body-small">
              <ng-container>
                <ng-template #defaultReview2>
                  <div class="testimonial17-fragment14">
                    <span class="testimonial17-text28">
                      As a teacher in a remote village, accessing healthcare was
                      always a challenge. Swasth Saarthi has made it convenient
                      for me to seek medical advice and get prescriptions
                      delivered to my doorstep. The mental wellness chatbot has
                      also helped me manage stress better.
                    </span>
                  </div>
                </ng-template>
                <ng-container
                  *ngTemplateOutlet="review2 ? review2 : defaultReview2"
                ></ng-container>
              </ng-container>
            </span>
          </div>
        </div>
      </div>
      <div class="thq-animated-card-bg-2">
        <div class="thq-animated-card-bg-1">
          <div data-animated="true" class="thq-card testimonial17-card3">
            <div class="testimonial17-container16">
              <img
                [attr.alt]="author3Alt"
                [attr.src]="author3Src"
                class="testimonial17-image3"
              />
              <div class="testimonial17-container17">
                <strong class="thq-body-large">
                  <ng-container>
                    <ng-template #defaultAuthor3Name>
                      <div class="testimonial17-fragment13">
                        <span class="testimonial17-text27">Amit Kumar</span>
                      </div>
                    </ng-template>
                    <ng-container
                      *ngTemplateOutlet="author3Name ? author3Name : defaultAuthor3Name"
                    ></ng-container>
                  </ng-container>
                </strong>
                <span class="thq-body-small">
                  <ng-container>
                    <ng-template #defaultAuthor3Position>
                      <div class="testimonial17-fragment19">
                        <span class="testimonial17-text33">
                          Local Shop Owner
                        </span>
                      </div>
                    </ng-template>
                    <ng-container
                      *ngTemplateOutlet="author3Position ? author3Position : defaultAuthor3Position"
                    ></ng-container>
                  </ng-container>
                </span>
              </div>
            </div>
            <span class="testimonial17-text20 thq-body-small">
              <ng-container>
                <ng-template #defaultReview3>
                  <div class="testimonial17-fragment22">
                    <span class="testimonial17-text36">
                      I never thought I could receive quality healthcare
                      services from the comfort of my shop until I discovered
                      Swasth Saarthi. The telemedicine consultations have been
                      prompt and effective, and the multi-language support is a
                      game-changer for our community.
                    </span>
                  </div>
                </ng-template>
                <ng-container
                  *ngTemplateOutlet="review3 ? review3 : defaultReview3"
                ></ng-container>
              </ng-container>
            </span>
          </div>
        </div>
      </div>
      <div class="thq-animated-card-bg-2">
        <div class="thq-animated-card-bg-1">
          <div data-animated="true" class="thq-card testimonial17-card4">
            <div class="testimonial17-container18">
              <img
                [attr.alt]="author4Alt"
                [attr.src]="author4Src"
                class="testimonial17-image4"
              />
              <div class="testimonial17-container19">
                <strong class="thq-body-large">
                  <ng-container>
                    <ng-template #defaultAuthor4Name>
                      <div class="testimonial17-fragment17">
                        <span class="testimonial17-text31">Priya Singh</span>
                      </div>
                    </ng-template>
                    <ng-container
                      *ngTemplateOutlet="author4Name ? author4Name : defaultAuthor4Name"
                    ></ng-container>
                  </ng-container>
                </strong>
                <span class="thq-body-small">
                  <ng-container>
                    <ng-template #defaultAuthor4Position>
                      <div class="testimonial17-fragment16">
                        <span class="testimonial17-text30">Social Worker</span>
                      </div>
                    </ng-template>
                    <ng-container
                      *ngTemplateOutlet="author4Position ? author4Position : defaultAuthor4Position"
                    ></ng-container>
                  </ng-container>
                </span>
              </div>
            </div>
            <span class="testimonial17-text23 thq-body-small">
              <ng-container>
                <ng-template #defaultReview4>
                  <div class="testimonial17-fragment23">
                    <span class="testimonial17-text37">
                      Working with marginalized communities, I have seen
                      firsthand the impact of Swasth Saarthi in bridging the
                      healthcare gap. The platform&apos;s integration with
                      government programs ensures that even the most vulnerable
                      populations have access to essential medical services.
                    </span>
                  </div>
                </ng-template>
                <ng-container
                  *ngTemplateOutlet="review4 ? review4 : defaultReview4"
                ></ng-container>
              </ng-container>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
